// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::super::models::*;
use serde::{Deserialize, Serialize};

crate::open_enum! {
    pub enum GetIssueRequestExpandVariant2 {
        RenderedFields => "renderedFields",
        Names => "names",
        Schema => "schema",
        Transitions => "transitions",
        Editmeta => "editmeta",
        Changelog => "changelog",
        VersionedRepresentations => "versionedRepresentations",
    }
}

crate::open_enum! {
    pub enum GetIssueRequestExpandUnion3 {
        RenderedFields => "renderedFields",
        Names => "names",
        Schema => "schema",
        Transitions => "transitions",
        Editmeta => "editmeta",
        Changelog => "changelog",
        VersionedRepresentations => "versionedRepresentations",
    }
}

/// Use [expand](#expansion) to include additional information about the issues in the response. This parameter accepts a comma-separated list. Expand options include:
///
///  *  `renderedFields` Returns field values rendered in HTML format.
///  *  `names` Returns the display name of each field.
///  *  `schema` Returns the schema describing a field type.
///  *  `transitions` Returns all possible transitions for the issue.
///  *  `editmeta` Returns information about how each field can be edited.
///  *  `changelog` Returns a list of recent updates to an issue, sorted by date, starting from the most recent.
///  *  `versionedRepresentations` Returns a JSON array for each version of a field's value, with the highest number representing the most recent version. Note: When included in the request, the `fields` parameter is ignored.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
#[allow(clippy::large_enum_variant)]
pub enum GetIssueRequestExpand {
    Variant0(String),
    Variant1(Vec<String>),
    Variant2(GetIssueRequestExpandVariant2),
    Variant3(Vec<GetIssueRequestExpandUnion3>),
}

crate::open_enum! {
    /// Whether the issue's subtasks are deleted when the issue is deleted.
    pub enum DeleteIssueRequestDeleteSubtasks {
        True => "true",
        False => "false",
    }
}

crate::open_enum! {
    pub enum GetTransitionsRequestExpandVariant2 {
        TransitionsFields => "transitions.fields",
    }
}

crate::open_enum! {
    pub enum GetTransitionsRequestExpandUnion3 {
        TransitionsFields => "transitions.fields",
    }
}

/// Use [expand](#expansion) to include additional information about transitions in the response. This parameter accepts `transitions.fields`, which returns information about the fields in the transition screen for each transition. Fields hidden from the screen are not returned. Use this information to populate the `fields` and `update` fields in [Transition issue](#api-rest-api-3-issue-issueIdOrKey-transitions-post).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
#[allow(clippy::large_enum_variant)]
pub enum GetTransitionsRequestExpand {
    Variant0(String),
    Variant1(Vec<String>),
    Variant2(GetTransitionsRequestExpandVariant2),
    Variant3(Vec<GetTransitionsRequestExpandUnion3>),
}

/// The Issues operations.
pub struct IssuesService<'a> {
    client: &'a crate::core::Client,
}

impl<'a> IssuesService<'a> {
    pub(crate) fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// Bulk fetch changelogs for multiple issues and filter by fields
    ///
    /// Returns a paginated list of all changelogs for given issues sorted by changelog date and issue IDs, starting from the oldest changelog and smallest issue ID.
    ///
    /// Issues are identified by their ID or key, and optionally changelogs can be filtered by their field IDs. You can request the changelogs of up to 1000 issues and can filter them by up to 10 field IDs.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the projects that the issues are in.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issues.
    pub fn get_bulk_changelogs(&self, bulk_changelog_request: BulkChangelogRequest) -> GetBulkChangelogsRequest<'a> {
        GetBulkChangelogsRequest::new(self.client, bulk_changelog_request)
    }

    /// Creates an issue or, where the option to create subtasks is enabled in Jira, a subtask. A transition may be applied, to move the issue or subtask to a workflow step other than the default start step, and issue properties set.
    ///
    /// The content of the issue or subtask is defined using `update` and `fields`. The fields that can be set in the issue or subtask are determined using the [ Get create issue metadata](#api-rest-api-3-issue-createmeta-get). These are the same fields that appear on the issue's create screen. Note that the `description`, `environment`, and any `textarea` type custom fields (multi-line text fields) take Atlassian Document Format content. Single line custom fields (`textfield`) accept a string and don't handle Atlassian Document Format content.
    ///
    /// Creating a subtask differs from creating an issue as follows:
    ///
    ///  *  `issueType` must be set to a subtask issue type (use [ Get create issue metadata](#api-rest-api-3-issue-createmeta-get) to find subtask issue types).
    ///  *  `parent` must contain the ID or key of the parent issue.
    ///
    /// In a next-gen project any issue may be made a child providing that the parent and child are members of the same project.
    ///
    /// **[Permissions](#permissions) required:** *Browse projects* and *Create issues* [project permissions](https://confluence.atlassian.com/x/yodKLg) for the project in which the issue or subtask is created.
    pub fn create_issue(&self, issue_update_details: IssueUpdateDetails) -> CreateIssueRequest<'a> {
        CreateIssueRequest::new(self.client, issue_update_details)
    }

    /// Creates upto **50** issues and, where the option to create subtasks is enabled in Jira, subtasks. Transitions may be applied, to move the issues or subtasks to a workflow step other than the default start step, and issue properties set.
    ///
    /// The content of each issue or subtask is defined using `update` and `fields`. The fields that can be set in the issue or subtask are determined using the [ Get create issue metadata](#api-rest-api-3-issue-createmeta-get). These are the same fields that appear on the issues' create screens. Note that the `description`, `environment`, and any `textarea` type custom fields (multi-line text fields) take Atlassian Document Format content. Single line custom fields (`textfield`) accept a string and don't handle Atlassian Document Format content.
    ///
    /// Creating a subtask differs from creating an issue as follows:
    ///
    ///  *  `issueType` must be set to a subtask issue type (use [ Get create issue metadata](#api-rest-api-3-issue-createmeta-get) to find subtask issue types).
    ///  *  `parent` the must contain the ID or key of the parent issue.
    ///
    /// **[Permissions](#permissions) required:** *Browse projects* and *Create issues* [project permissions](https://confluence.atlassian.com/x/yodKLg) for the project in which each issue or subtask is created.
    pub fn create_issues(&self, issues_update: IssuesUpdate) -> CreateIssuesRequest<'a> {
        CreateIssuesRequest::new(self.client, issues_update)
    }

    /// Returns the details for a set of requested issues.
    ///
    /// By default you can request up to 100 issues in a single call. You can request up to 1000 issues in a single call when the request is shaped so that it can be served efficiently, that is, when *all* of the following are true:
    ///
    ///  *  the `fields` parameter explicitly names at least one field to include — a request that contains only exclusions is **not** eligible, and neither are the `*all` and `*navigable` wildcards or the default navigable field set, because the number of resolved fields depends on the site's configuration;
    ///  *  no more than 100 fields are explicitly included;
    ///  *  none of the included fields returns multiple values (for example `comment`, `worklog`, or `attachment`); and
    ///  *  the `expand` parameter does not include `changelog`, `editmeta`, `operations`, `renderedFields`, `transitions`, or `versionedRepresentations`.
    ///
    /// Requests that do not meet all of these conditions can include at most 100 issues; larger requests are rejected with a 400 error.
    ///
    /// Each issue is identified by its ID or key, however, if the identifier doesn't match an issue, a case-insensitive search and check for moved issues is performed. If a matching issue is found its details are returned, a 302 or other redirect is **not** returned.
    ///
    /// Issues will be returned in ascending `id` order. If there are errors, Jira will return a list of issues which couldn't be fetched along with error messages.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:** Issues are included in the response where the user has:
    ///
    ///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    pub fn bulk_fetch_issues(&self, bulk_fetch_issue_request: BulkFetchIssueRequest) -> BulkFetchIssuesRequest<'a> {
        BulkFetchIssuesRequest::new(self.client, bulk_fetch_issue_request)
    }

    /// Returns a page of issue type metadata for a specified project. Use the information to populate the requests in [ Create issue](#api-rest-api-3-issue-post) and [Create issues](#api-rest-api-3-issue-bulk-post).
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:** *Create issues* [project permission](https://confluence.atlassian.com/x/yodKLg) in the requested projects.
    pub fn get_create_issue_meta_issue_types(
        &self,
        project_id_or_key: impl Into<String>,
    ) -> GetCreateIssueMetaIssueTypesRequest<'a> {
        GetCreateIssueMetaIssueTypesRequest::new(self.client, project_id_or_key)
    }

    /// Returns a page of field metadata for a specified project and issuetype id. Use the information to populate the requests in [ Create issue](#api-rest-api-3-issue-post) and [Create issues](#api-rest-api-3-issue-bulk-post).
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:** *Create issues* [project permission](https://confluence.atlassian.com/x/yodKLg) in the requested projects.
    pub fn get_create_issue_meta_issue_type_id(
        &self,
        project_id_or_key: impl Into<String>,
        issue_type_id: impl Into<String>,
    ) -> GetCreateIssueMetaIssueTypeIdRequest<'a> {
        GetCreateIssueMetaIssueTypeIdRequest::new(self.client, project_id_or_key, issue_type_id)
    }

    /// Returns the details for an issue.
    ///
    /// The issue is identified by its ID or key, however, if the identifier doesn't match an issue, a case-insensitive search and check for moved issues is performed. If a matching issue is found its details are returned, a 302 or other redirect is **not** returned. The issue key returned in the response is the key of the issue found.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    pub fn get_issue(&self, issue_id_or_key: impl Into<String>) -> GetIssueRequest<'a> {
        GetIssueRequest::new(self.client, issue_id_or_key)
    }

    /// Edits an issue. Issue properties may be updated as part of the edit. Please note that issue transition is not supported and is ignored here. To transition an issue, please use [Transition issue](#api-rest-api-3-issue-issueIdOrKey-transitions-post).
    ///
    /// The edits to the issue's fields are defined using `update` and `fields`. The fields that can be edited are determined using [ Get edit issue metadata](#api-rest-api-3-issue-issueIdOrKey-editmeta-get).
    ///
    /// **Note:** This endpoint doesn't check screen configurations to determine if a field is editable. For more context, see the [Deprecation of override screen security](https://community.developer.atlassian.com/t/deprecation-of-override-screen-security/97153) announcement.
    ///
    /// The parent field may be set by key or ID. For standard issue types, the parent may be removed by setting `update.parent.set.none` to *true*. Note that the `description`, `environment`, and any `textarea` type custom fields (multi-line text fields) take Atlassian Document Format content. Single line custom fields (`textfield`) accept a string and don't handle Atlassian Document Format content.
    ///
    /// Connect apps having an app user with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), can override the screen security configuration using `overrideScreenSecurity` and `overrideEditableFlag`.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse projects* and *Edit issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    pub fn edit_issue(
        &self,
        issue_id_or_key: impl Into<String>,
        issue_update_details: IssueUpdateDetails,
    ) -> EditIssueRequest<'a> {
        EditIssueRequest::new(self.client, issue_id_or_key, issue_update_details)
    }

    /// Deletes an issue.
    ///
    /// An issue cannot be deleted if it has one or more subtasks. To delete an issue with subtasks, set `deleteSubtasks`. This causes the issue's subtasks to be deleted with the issue.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse projects* and *Delete issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    pub fn delete_issue(&self, issue_id_or_key: impl Into<String>) -> DeleteIssueRequest<'a> {
        DeleteIssueRequest::new(self.client, issue_id_or_key)
    }

    /// Assigns an issue to a user. Use this operation when the calling user does not have the *Edit Issues* permission but has the *Assign issue* permission for the project that the issue is in.
    ///
    /// If `name` or `accountId` is set to:
    ///
    ///  *  `"-1"`, the issue is assigned to the default assignee for the project.
    ///  *  `null`, the issue is set to unassigned.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse Projects* and *Assign Issues* [ project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    pub fn assign_issue(
        &self,
        issue_id_or_key: impl Into<String>,
        dashboard_user: DashboardUser,
    ) -> AssignIssueRequest<'a> {
        AssignIssueRequest::new(self.client, issue_id_or_key, dashboard_user)
    }

    /// Returns a [paginated](#pagination) list of all changelogs for an issue sorted by date, starting from the oldest.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    pub fn get_change_logs(&self, issue_id_or_key: impl Into<String>) -> GetChangeLogsRequest<'a> {
        GetChangeLogsRequest::new(self.client, issue_id_or_key)
    }

    /// Returns changelogs for an issue specified by a list of changelog IDs.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    pub fn get_change_logs_by_ids(
        &self,
        issue_id_or_key: impl Into<String>,
        issue_changelog_ids: IssueChangelogIds,
    ) -> GetChangeLogsByIdsRequest<'a> {
        GetChangeLogsByIdsRequest::new(self.client, issue_id_or_key, issue_changelog_ids)
    }

    /// Returns the edit screen fields for an issue that are visible to and editable by the user. Use the information to populate the requests in [Edit issue](#api-rest-api-3-issue-issueIdOrKey-put).
    ///
    /// This endpoint will check for these conditions:
    ///
    /// 1.  Field is available on a field screen - through screen, screen scheme, issue type screen scheme, and issue type scheme configuration. `overrideScreenSecurity=true` skips this condition.
    /// 2.  Field is visible in the [field configuration](https://support.atlassian.com/jira-cloud-administration/docs/change-a-field-configuration/). `overrideScreenSecurity=true` skips this condition.
    /// 3.  Field is shown on the issue: each field has different conditions here. For example: Attachment field only shows if attachments are enabled. Assignee only shows if user has permissions to assign the issue.
    /// 4.  If a field is custom then it must have valid custom field context, applicable for its project and issue type. All system fields are assumed to have context in all projects and all issue types.
    /// 5.  Issue has a project, issue type, and status defined.
    /// 6.  Issue is assigned to a valid workflow, and the current status has assigned a workflow step. `overrideEditableFlag=true` skips this condition.
    /// 7.  The current workflow step is editable. This is true by default, but [can be disabled by setting](https://support.atlassian.com/jira-cloud-administration/docs/use-workflow-properties/) the `jira.issue.editable` property to `false`. `overrideEditableFlag=true` skips this condition.
    /// 8.  User has [Edit issues permission](https://support.atlassian.com/jira-cloud-administration/docs/permissions-for-company-managed-projects/).
    /// 9.  Workflow permissions allow editing a field. This is true by default but [can be modified](https://support.atlassian.com/jira-cloud-administration/docs/use-workflow-properties/) using `jira.permission.*` workflow properties.
    ///
    /// Fields hidden using [Issue layout settings page](https://support.atlassian.com/jira-software-cloud/docs/configure-field-layout-in-the-issue-view/) remain editable.
    ///
    /// Connect apps having an app user with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), can return additional details using:
    ///
    ///  *  `overrideScreenSecurity` When this flag is `true`, then this endpoint skips checking if fields are available through screens, and field configuration (conditions 1. and 2. from the list above).
    ///  *  `overrideEditableFlag` When this flag is `true`, then this endpoint skips checking if workflow is present and if the current step is editable (conditions 6. and 7. from the list above).
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    ///
    /// Note: For any fields to be editable the user must have the *Edit issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the issue.
    pub fn get_edit_issue_meta(&self, issue_id_or_key: impl Into<String>) -> GetEditIssueMetaRequest<'a> {
        GetEditIssueMetaRequest::new(self.client, issue_id_or_key)
    }

    /// Creates an email notification for an issue and adds it to the mail queue.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    pub fn notify(&self, issue_id_or_key: impl Into<String>, notification: Notification) -> NotifyRequest<'a> {
        NotifyRequest::new(self.client, issue_id_or_key, notification)
    }

    /// Returns either all transitions or a transition that can be performed by the user on an issue, based on the issue's status.
    ///
    /// Note, if a request is made for a transition that does not exist or cannot be performed on the issue, given its status, the response will return any empty transitions list.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required: A list or transition is returned only when the user has:**
    ///
    ///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    ///
    /// However, if the user does not have the *Transition issues* [ project permission](https://confluence.atlassian.com/x/yodKLg) the response will not list any transitions.
    pub fn get_transitions(&self, issue_id_or_key: impl Into<String>) -> GetTransitionsRequest<'a> {
        GetTransitionsRequest::new(self.client, issue_id_or_key)
    }

    /// Performs an issue transition and, if the transition has a screen, updates the fields from the transition screen.
    ///
    /// sortByCategory To update the fields on the transition screen, specify the fields in the `fields` or `update` parameters in the request body. Get details about the fields using [ Get transitions](#api-rest-api-3-issue-issueIdOrKey-transitions-get) with the `transitions.fields` expand.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse projects* and *Transition issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    pub fn do_transition(
        &self,
        issue_id_or_key: impl Into<String>,
        issue_update_details: IssueUpdateDetails,
    ) -> DoTransitionRequest<'a> {
        DoTransitionRequest::new(self.client, issue_id_or_key, issue_update_details)
    }
}

/// Bulk fetch changelogs for multiple issues and filter by fields
///
/// Returns a paginated list of all changelogs for given issues sorted by changelog date and issue IDs, starting from the oldest changelog and smallest issue ID.
///
/// Issues are identified by their ID or key, and optionally changelogs can be filtered by their field IDs. You can request the changelogs of up to 1000 issues and can filter them by up to 10 field IDs.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the projects that the issues are in.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issues.
pub struct GetBulkChangelogsRequest<'a> {
    client: &'a crate::core::Client,
    bulk_changelog_request: BulkChangelogRequest,
}

impl<'a> GetBulkChangelogsRequest<'a> {
    fn new(client: &'a crate::core::Client, bulk_changelog_request: BulkChangelogRequest) -> Self {
        Self { client, bulk_changelog_request }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config =
            crate::core::RequestConfig::new(crate::core::Method::POST, "/rest/api/3/changelog/bulkfetch".to_owned());

        let body = match serde_json::to_value(&self.bulk_changelog_request)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<BulkChangelogResponse> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Creates an issue or, where the option to create subtasks is enabled in Jira, a subtask. A transition may be applied, to move the issue or subtask to a workflow step other than the default start step, and issue properties set.
///
/// The content of the issue or subtask is defined using `update` and `fields`. The fields that can be set in the issue or subtask are determined using the [ Get create issue metadata](#api-rest-api-3-issue-createmeta-get). These are the same fields that appear on the issue's create screen. Note that the `description`, `environment`, and any `textarea` type custom fields (multi-line text fields) take Atlassian Document Format content. Single line custom fields (`textfield`) accept a string and don't handle Atlassian Document Format content.
///
/// Creating a subtask differs from creating an issue as follows:
///
///  *  `issueType` must be set to a subtask issue type (use [ Get create issue metadata](#api-rest-api-3-issue-createmeta-get) to find subtask issue types).
///  *  `parent` must contain the ID or key of the parent issue.
///
/// In a next-gen project any issue may be made a child providing that the parent and child are members of the same project.
///
/// **[Permissions](#permissions) required:** *Browse projects* and *Create issues* [project permissions](https://confluence.atlassian.com/x/yodKLg) for the project in which the issue or subtask is created.
pub struct CreateIssueRequest<'a> {
    client: &'a crate::core::Client,
    update_history: Option<bool>,
    issue_update_details: IssueUpdateDetails,
}

impl<'a> CreateIssueRequest<'a> {
    fn new(client: &'a crate::core::Client, issue_update_details: IssueUpdateDetails) -> Self {
        Self { client, issue_update_details, update_history: None }
    }

    /// Whether the project in which the issue is created is added to the user's **Recently viewed** project list, as shown under **Projects** in Jira. When provided, the issue type and request type are added to the user's history for a project. These values are then used to provide defaults on the issue create screen.
    #[must_use]
    pub fn update_history(mut self, value: bool) -> Self {
        self.update_history = Some(value);

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(crate::core::Method::POST, "/rest/api/3/issue".to_owned());

        if let Some(value) = &self.update_history {
            config.query.push(("updateHistory".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        let body = match serde_json::to_value(&self.issue_update_details)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<CreatedIssue> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Creates upto **50** issues and, where the option to create subtasks is enabled in Jira, subtasks. Transitions may be applied, to move the issues or subtasks to a workflow step other than the default start step, and issue properties set.
///
/// The content of each issue or subtask is defined using `update` and `fields`. The fields that can be set in the issue or subtask are determined using the [ Get create issue metadata](#api-rest-api-3-issue-createmeta-get). These are the same fields that appear on the issues' create screens. Note that the `description`, `environment`, and any `textarea` type custom fields (multi-line text fields) take Atlassian Document Format content. Single line custom fields (`textfield`) accept a string and don't handle Atlassian Document Format content.
///
/// Creating a subtask differs from creating an issue as follows:
///
///  *  `issueType` must be set to a subtask issue type (use [ Get create issue metadata](#api-rest-api-3-issue-createmeta-get) to find subtask issue types).
///  *  `parent` the must contain the ID or key of the parent issue.
///
/// **[Permissions](#permissions) required:** *Browse projects* and *Create issues* [project permissions](https://confluence.atlassian.com/x/yodKLg) for the project in which each issue or subtask is created.
pub struct CreateIssuesRequest<'a> {
    client: &'a crate::core::Client,
    issues_update: IssuesUpdate,
}

impl<'a> CreateIssuesRequest<'a> {
    fn new(client: &'a crate::core::Client, issues_update: IssuesUpdate) -> Self {
        Self { client, issues_update }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config =
            crate::core::RequestConfig::new(crate::core::Method::POST, "/rest/api/3/issue/bulk".to_owned());

        let body = match serde_json::to_value(&self.issues_update)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<CreatedIssues> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Returns the details for a set of requested issues.
///
/// By default you can request up to 100 issues in a single call. You can request up to 1000 issues in a single call when the request is shaped so that it can be served efficiently, that is, when *all* of the following are true:
///
///  *  the `fields` parameter explicitly names at least one field to include — a request that contains only exclusions is **not** eligible, and neither are the `*all` and `*navigable` wildcards or the default navigable field set, because the number of resolved fields depends on the site's configuration;
///  *  no more than 100 fields are explicitly included;
///  *  none of the included fields returns multiple values (for example `comment`, `worklog`, or `attachment`); and
///  *  the `expand` parameter does not include `changelog`, `editmeta`, `operations`, `renderedFields`, `transitions`, or `versionedRepresentations`.
///
/// Requests that do not meet all of these conditions can include at most 100 issues; larger requests are rejected with a 400 error.
///
/// Each issue is identified by its ID or key, however, if the identifier doesn't match an issue, a case-insensitive search and check for moved issues is performed. If a matching issue is found its details are returned, a 302 or other redirect is **not** returned.
///
/// Issues will be returned in ascending `id` order. If there are errors, Jira will return a list of issues which couldn't be fetched along with error messages.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:** Issues are included in the response where the user has:
///
///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
pub struct BulkFetchIssuesRequest<'a> {
    client: &'a crate::core::Client,
    bulk_fetch_issue_request: BulkFetchIssueRequest,
}

impl<'a> BulkFetchIssuesRequest<'a> {
    fn new(client: &'a crate::core::Client, bulk_fetch_issue_request: BulkFetchIssueRequest) -> Self {
        Self { client, bulk_fetch_issue_request }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config =
            crate::core::RequestConfig::new(crate::core::Method::POST, "/rest/api/3/issue/bulkfetch".to_owned());

        let body = match serde_json::to_value(&self.bulk_fetch_issue_request)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<BulkIssueResults> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Returns a page of issue type metadata for a specified project. Use the information to populate the requests in [ Create issue](#api-rest-api-3-issue-post) and [Create issues](#api-rest-api-3-issue-bulk-post).
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:** *Create issues* [project permission](https://confluence.atlassian.com/x/yodKLg) in the requested projects.
pub struct GetCreateIssueMetaIssueTypesRequest<'a> {
    client: &'a crate::core::Client,
    project_id_or_key: String,
    start_at: Option<i64>,
    max_results: Option<i64>,
}

impl<'a> GetCreateIssueMetaIssueTypesRequest<'a> {
    fn new(client: &'a crate::core::Client, project_id_or_key: impl Into<String>) -> Self {
        Self { client, project_id_or_key: project_id_or_key.into(), start_at: None, max_results: None }
    }

    /// The index of the first item to return in a page of results (page offset).
    #[must_use]
    pub fn start_at(mut self, value: i64) -> Self {
        self.start_at = Some(value);

        self
    }

    /// The maximum number of items to return per page.
    #[must_use]
    pub fn max_results(mut self, value: i64) -> Self {
        self.max_results = Some(value);

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::GET,
            format!("/rest/api/3/issue/createmeta/{}/issuetypes", self.project_id_or_key),
        );

        if let Some(value) = &self.start_at {
            config.query.push(("startAt".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.max_results {
            config.query.push(("maxResults".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<PageOfCreateMetaIssueTypes> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Returns a page of field metadata for a specified project and issuetype id. Use the information to populate the requests in [ Create issue](#api-rest-api-3-issue-post) and [Create issues](#api-rest-api-3-issue-bulk-post).
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:** *Create issues* [project permission](https://confluence.atlassian.com/x/yodKLg) in the requested projects.
pub struct GetCreateIssueMetaIssueTypeIdRequest<'a> {
    client: &'a crate::core::Client,
    project_id_or_key: String,
    issue_type_id: String,
    start_at: Option<i64>,
    max_results: Option<i64>,
}

impl<'a> GetCreateIssueMetaIssueTypeIdRequest<'a> {
    fn new(
        client: &'a crate::core::Client,
        project_id_or_key: impl Into<String>,
        issue_type_id: impl Into<String>,
    ) -> Self {
        Self {
            client,
            project_id_or_key: project_id_or_key.into(),
            issue_type_id: issue_type_id.into(),
            start_at: None,
            max_results: None,
        }
    }

    /// The index of the first item to return in a page of results (page offset).
    #[must_use]
    pub fn start_at(mut self, value: i64) -> Self {
        self.start_at = Some(value);

        self
    }

    /// The maximum number of items to return per page.
    #[must_use]
    pub fn max_results(mut self, value: i64) -> Self {
        self.max_results = Some(value);

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::GET,
            format!("/rest/api/3/issue/createmeta/{}/issuetypes/{}", self.project_id_or_key, self.issue_type_id),
        );

        if let Some(value) = &self.start_at {
            config.query.push(("startAt".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.max_results {
            config.query.push(("maxResults".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<PageOfCreateMetaIssueTypeWithField> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Returns the details for an issue.
///
/// The issue is identified by its ID or key, however, if the identifier doesn't match an issue, a case-insensitive search and check for moved issues is performed. If a matching issue is found its details are returned, a 302 or other redirect is **not** returned. The issue key returned in the response is the key of the issue found.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
pub struct GetIssueRequest<'a> {
    client: &'a crate::core::Client,
    issue_id_or_key: String,
    fields: Option<Vec<String>>,
    fields_by_keys: Option<bool>,
    expand: Option<GetIssueRequestExpand>,
    properties: Option<Vec<String>>,
    update_history: Option<bool>,
    fail_fast: Option<bool>,
}

impl<'a> GetIssueRequest<'a> {
    fn new(client: &'a crate::core::Client, issue_id_or_key: impl Into<String>) -> Self {
        Self {
            client,
            issue_id_or_key: issue_id_or_key.into(),
            fields: None,
            fields_by_keys: None,
            expand: None,
            properties: None,
            update_history: None,
            fail_fast: None,
        }
    }

    /// A list of fields to return for the issue. This parameter accepts a comma-separated list. Use it to retrieve a subset of fields. Allowed values:
    ///
    ///  *  `*all` Returns all fields.
    ///  *  `*navigable` Returns navigable fields.
    ///  *  Any issue field, prefixed with a minus to exclude.
    ///
    /// Examples:
    ///
    ///  *  `summary,comment` Returns only the summary and comments fields.
    ///  *  `-description` Returns all (default) fields except description.
    ///  *  `*navigable,-comment` Returns all navigable fields except comment.
    ///
    /// This parameter may be specified multiple times. For example, `fields=field1,field2& fields=field3`.
    ///
    /// Note: All fields are returned by default. This differs from [Search for issues using JQL (GET)](#api-rest-api-3-search-get) and [Search for issues using JQL (POST)](#api-rest-api-3-search-post) where the default is all navigable fields.
    #[must_use]
    pub fn fields(mut self, value: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.fields = Some(value.into_iter().map(Into::into).collect());

        self
    }

    /// Whether fields in `fields` are referenced by keys rather than IDs. This parameter is useful where fields have been added by a connect app and a field's key may differ from its ID.
    #[must_use]
    pub fn fields_by_keys(mut self, value: bool) -> Self {
        self.fields_by_keys = Some(value);

        self
    }

    /// Use [expand](#expansion) to include additional information about the issues in the response. This parameter accepts a comma-separated list. Expand options include:
    ///
    ///  *  `renderedFields` Returns field values rendered in HTML format.
    ///  *  `names` Returns the display name of each field.
    ///  *  `schema` Returns the schema describing a field type.
    ///  *  `transitions` Returns all possible transitions for the issue.
    ///  *  `editmeta` Returns information about how each field can be edited.
    ///  *  `changelog` Returns a list of recent updates to an issue, sorted by date, starting from the most recent.
    ///  *  `versionedRepresentations` Returns a JSON array for each version of a field's value, with the highest number representing the most recent version. Note: When included in the request, the `fields` parameter is ignored.
    #[must_use]
    pub fn expand(mut self, value: GetIssueRequestExpand) -> Self {
        self.expand = Some(value);

        self
    }

    /// A list of issue properties to return for the issue. This parameter accepts a comma-separated list. Allowed values:
    ///
    ///  *  `*all` Returns all issue properties.
    ///  *  Any issue property key, prefixed with a minus to exclude.
    ///
    /// Examples:
    ///
    ///  *  `*all` Returns all properties.
    ///  *  `*all,-prop1` Returns all properties except `prop1`.
    ///  *  `prop1,prop2` Returns `prop1` and `prop2` properties.
    ///
    /// This parameter may be specified multiple times. For example, `properties=prop1,prop2& properties=prop3`.
    #[must_use]
    pub fn properties(mut self, value: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.properties = Some(value.into_iter().map(Into::into).collect());

        self
    }

    /// Whether the project in which the issue is created is added to the user's **Recently viewed** project list, as shown under **Projects** in Jira. This also populates the [JQL issues search](#api-rest-api-3-search-get) `lastViewed` field.
    #[must_use]
    pub fn update_history(mut self, value: bool) -> Self {
        self.update_history = Some(value);

        self
    }

    /// Whether to fail the request quickly in case of an error while loading fields for an issue. For `failFast=true`, if one field fails, the entire operation fails. For `failFast=false`, the operation will continue even if a field fails. It will return a valid response, but without values for the failed field(s).
    #[must_use]
    pub fn fail_fast(mut self, value: bool) -> Self {
        self.fail_fast = Some(value);

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::GET,
            format!("/rest/api/3/issue/{}", self.issue_id_or_key),
        );

        if let Some(value) = &self.fields {
            config.query.push(("fields".to_owned(), crate::core::QueryValue::List(value.clone())));
        }

        if let Some(value) = &self.fields_by_keys {
            config.query.push(("fieldsByKeys".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.expand {
            config.query.push(("expand".to_owned(), crate::core::QueryValue::from_serializable(value)?));
        }

        if let Some(value) = &self.properties {
            config.query.push(("properties".to_owned(), crate::core::QueryValue::List(value.clone())));
        }

        if let Some(value) = &self.update_history {
            config.query.push(("updateHistory".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.fail_fast {
            config.query.push(("failFast".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<Issue> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Edits an issue. Issue properties may be updated as part of the edit. Please note that issue transition is not supported and is ignored here. To transition an issue, please use [Transition issue](#api-rest-api-3-issue-issueIdOrKey-transitions-post).
///
/// The edits to the issue's fields are defined using `update` and `fields`. The fields that can be edited are determined using [ Get edit issue metadata](#api-rest-api-3-issue-issueIdOrKey-editmeta-get).
///
/// **Note:** This endpoint doesn't check screen configurations to determine if a field is editable. For more context, see the [Deprecation of override screen security](https://community.developer.atlassian.com/t/deprecation-of-override-screen-security/97153) announcement.
///
/// The parent field may be set by key or ID. For standard issue types, the parent may be removed by setting `update.parent.set.none` to *true*. Note that the `description`, `environment`, and any `textarea` type custom fields (multi-line text fields) take Atlassian Document Format content. Single line custom fields (`textfield`) accept a string and don't handle Atlassian Document Format content.
///
/// Connect apps having an app user with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), can override the screen security configuration using `overrideScreenSecurity` and `overrideEditableFlag`.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse projects* and *Edit issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
pub struct EditIssueRequest<'a> {
    client: &'a crate::core::Client,
    issue_id_or_key: String,
    notify_users: Option<bool>,
    override_screen_security: Option<bool>,
    override_editable_flag: Option<bool>,
    return_issue: Option<bool>,
    expand: Option<String>,
    issue_update_details: IssueUpdateDetails,
}

impl<'a> EditIssueRequest<'a> {
    fn new(
        client: &'a crate::core::Client,
        issue_id_or_key: impl Into<String>,
        issue_update_details: IssueUpdateDetails,
    ) -> Self {
        Self {
            client,
            issue_id_or_key: issue_id_or_key.into(),
            issue_update_details,
            notify_users: None,
            override_screen_security: None,
            override_editable_flag: None,
            return_issue: None,
            expand: None,
        }
    }

    /// Whether a notification email about the issue update is sent to all watchers. To disable the notification, administer Jira or administer project permissions are required. If the user doesn't have the necessary permission the request is ignored.
    #[must_use]
    pub fn notify_users(mut self, value: bool) -> Self {
        self.notify_users = Some(value);

        self
    }

    /// Whether screen security is overridden to enable hidden fields to be edited. Available to Connect and Forge app users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    #[must_use]
    pub fn override_screen_security(mut self, value: bool) -> Self {
        self.override_screen_security = Some(value);

        self
    }

    /// Whether screen security is overridden to enable uneditable fields to be edited. Available to Connect and Forge app users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    #[must_use]
    pub fn override_editable_flag(mut self, value: bool) -> Self {
        self.override_editable_flag = Some(value);

        self
    }

    /// Whether the response should contain the issue with fields edited in this request. The returned issue will have the same format as in the [Get issue API](#api-rest-api-3-issue-issueidorkey-get).
    #[must_use]
    pub fn return_issue(mut self, value: bool) -> Self {
        self.return_issue = Some(value);

        self
    }

    /// The Get issue API expand parameter to use in the response if the `returnIssue` parameter is `true`.
    #[must_use]
    pub fn expand(mut self, value: impl Into<String>) -> Self {
        self.expand = Some(value.into());

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::PUT,
            format!("/rest/api/3/issue/{}", self.issue_id_or_key),
        );

        if let Some(value) = &self.notify_users {
            config.query.push(("notifyUsers".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.override_screen_security {
            config
                .query
                .push(("overrideScreenSecurity".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.override_editable_flag {
            config.query.push(("overrideEditableFlag".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.return_issue {
            config.query.push(("returnIssue".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.expand {
            config.query.push(("expand".to_owned(), crate::core::QueryValue::Scalar(value.clone())));
        }

        let body = match serde_json::to_value(&self.issue_update_details)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Deletes an issue.
///
/// An issue cannot be deleted if it has one or more subtasks. To delete an issue with subtasks, set `deleteSubtasks`. This causes the issue's subtasks to be deleted with the issue.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse projects* and *Delete issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
pub struct DeleteIssueRequest<'a> {
    client: &'a crate::core::Client,
    issue_id_or_key: String,
    delete_subtasks: Option<DeleteIssueRequestDeleteSubtasks>,
}

impl<'a> DeleteIssueRequest<'a> {
    fn new(client: &'a crate::core::Client, issue_id_or_key: impl Into<String>) -> Self {
        Self { client, issue_id_or_key: issue_id_or_key.into(), delete_subtasks: None }
    }

    /// Whether the issue's subtasks are deleted when the issue is deleted.
    #[must_use]
    pub fn delete_subtasks(mut self, value: impl Into<DeleteIssueRequestDeleteSubtasks>) -> Self {
        self.delete_subtasks = Some(value.into());

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::DELETE,
            format!("/rest/api/3/issue/{}", self.issue_id_or_key),
        );

        if let Some(value) = &self.delete_subtasks {
            config.query.push(("deleteSubtasks".to_owned(), crate::core::QueryValue::from_serializable(value)?));
        }

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Assigns an issue to a user. Use this operation when the calling user does not have the *Edit Issues* permission but has the *Assign issue* permission for the project that the issue is in.
///
/// If `name` or `accountId` is set to:
///
///  *  `"-1"`, the issue is assigned to the default assignee for the project.
///  *  `null`, the issue is set to unassigned.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse Projects* and *Assign Issues* [ project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
pub struct AssignIssueRequest<'a> {
    client: &'a crate::core::Client,
    issue_id_or_key: String,
    dashboard_user: DashboardUser,
}

impl<'a> AssignIssueRequest<'a> {
    fn new(client: &'a crate::core::Client, issue_id_or_key: impl Into<String>, dashboard_user: DashboardUser) -> Self {
        Self { client, issue_id_or_key: issue_id_or_key.into(), dashboard_user }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::PUT,
            format!("/rest/api/3/issue/{}/assignee", self.issue_id_or_key),
        );

        let body = match serde_json::to_value(&self.dashboard_user)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Returns a [paginated](#pagination) list of all changelogs for an issue sorted by date, starting from the oldest.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
pub struct GetChangeLogsRequest<'a> {
    client: &'a crate::core::Client,
    issue_id_or_key: String,
    start_at: Option<i64>,
    max_results: Option<i64>,
}

impl<'a> GetChangeLogsRequest<'a> {
    fn new(client: &'a crate::core::Client, issue_id_or_key: impl Into<String>) -> Self {
        Self { client, issue_id_or_key: issue_id_or_key.into(), start_at: None, max_results: None }
    }

    /// The index of the first item to return in a page of results (page offset).
    #[must_use]
    pub fn start_at(mut self, value: i64) -> Self {
        self.start_at = Some(value);

        self
    }

    /// The maximum number of items to return per page.
    #[must_use]
    pub fn max_results(mut self, value: i64) -> Self {
        self.max_results = Some(value);

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::GET,
            format!("/rest/api/3/issue/{}/changelog", self.issue_id_or_key),
        );

        if let Some(value) = &self.start_at {
            config.query.push(("startAt".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.max_results {
            config.query.push(("maxResults".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<Page<Changelog>> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Returns changelogs for an issue specified by a list of changelog IDs.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
pub struct GetChangeLogsByIdsRequest<'a> {
    client: &'a crate::core::Client,
    issue_id_or_key: String,
    issue_changelog_ids: IssueChangelogIds,
}

impl<'a> GetChangeLogsByIdsRequest<'a> {
    fn new(
        client: &'a crate::core::Client,
        issue_id_or_key: impl Into<String>,
        issue_changelog_ids: IssueChangelogIds,
    ) -> Self {
        Self { client, issue_id_or_key: issue_id_or_key.into(), issue_changelog_ids }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::POST,
            format!("/rest/api/3/issue/{}/changelog/list", self.issue_id_or_key),
        );

        let body = match serde_json::to_value(&self.issue_changelog_ids)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<PageOfChangelogs> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Returns the edit screen fields for an issue that are visible to and editable by the user. Use the information to populate the requests in [Edit issue](#api-rest-api-3-issue-issueIdOrKey-put).
///
/// This endpoint will check for these conditions:
///
/// 1.  Field is available on a field screen - through screen, screen scheme, issue type screen scheme, and issue type scheme configuration. `overrideScreenSecurity=true` skips this condition.
/// 2.  Field is visible in the [field configuration](https://support.atlassian.com/jira-cloud-administration/docs/change-a-field-configuration/). `overrideScreenSecurity=true` skips this condition.
/// 3.  Field is shown on the issue: each field has different conditions here. For example: Attachment field only shows if attachments are enabled. Assignee only shows if user has permissions to assign the issue.
/// 4.  If a field is custom then it must have valid custom field context, applicable for its project and issue type. All system fields are assumed to have context in all projects and all issue types.
/// 5.  Issue has a project, issue type, and status defined.
/// 6.  Issue is assigned to a valid workflow, and the current status has assigned a workflow step. `overrideEditableFlag=true` skips this condition.
/// 7.  The current workflow step is editable. This is true by default, but [can be disabled by setting](https://support.atlassian.com/jira-cloud-administration/docs/use-workflow-properties/) the `jira.issue.editable` property to `false`. `overrideEditableFlag=true` skips this condition.
/// 8.  User has [Edit issues permission](https://support.atlassian.com/jira-cloud-administration/docs/permissions-for-company-managed-projects/).
/// 9.  Workflow permissions allow editing a field. This is true by default but [can be modified](https://support.atlassian.com/jira-cloud-administration/docs/use-workflow-properties/) using `jira.permission.*` workflow properties.
///
/// Fields hidden using [Issue layout settings page](https://support.atlassian.com/jira-software-cloud/docs/configure-field-layout-in-the-issue-view/) remain editable.
///
/// Connect apps having an app user with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), can return additional details using:
///
///  *  `overrideScreenSecurity` When this flag is `true`, then this endpoint skips checking if fields are available through screens, and field configuration (conditions 1. and 2. from the list above).
///  *  `overrideEditableFlag` When this flag is `true`, then this endpoint skips checking if workflow is present and if the current step is editable (conditions 6. and 7. from the list above).
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
///
/// Note: For any fields to be editable the user must have the *Edit issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the issue.
pub struct GetEditIssueMetaRequest<'a> {
    client: &'a crate::core::Client,
    issue_id_or_key: String,
    override_screen_security: Option<bool>,
    override_editable_flag: Option<bool>,
}

impl<'a> GetEditIssueMetaRequest<'a> {
    fn new(client: &'a crate::core::Client, issue_id_or_key: impl Into<String>) -> Self {
        Self {
            client,
            issue_id_or_key: issue_id_or_key.into(),
            override_screen_security: None,
            override_editable_flag: None,
        }
    }

    /// Whether hidden fields are returned. Available to Connect and Forge app users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    #[must_use]
    pub fn override_screen_security(mut self, value: bool) -> Self {
        self.override_screen_security = Some(value);

        self
    }

    /// Whether non-editable fields are returned. Available to Connect and Forge app users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    #[must_use]
    pub fn override_editable_flag(mut self, value: bool) -> Self {
        self.override_editable_flag = Some(value);

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::GET,
            format!("/rest/api/3/issue/{}/editmeta", self.issue_id_or_key),
        );

        if let Some(value) = &self.override_screen_security {
            config
                .query
                .push(("overrideScreenSecurity".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.override_editable_flag {
            config.query.push(("overrideEditableFlag".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<IssueUpdateMetadata> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Creates an email notification for an issue and adds it to the mail queue.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
pub struct NotifyRequest<'a> {
    client: &'a crate::core::Client,
    issue_id_or_key: String,
    notification: Notification,
}

impl<'a> NotifyRequest<'a> {
    fn new(client: &'a crate::core::Client, issue_id_or_key: impl Into<String>, notification: Notification) -> Self {
        Self { client, issue_id_or_key: issue_id_or_key.into(), notification }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::POST,
            format!("/rest/api/3/issue/{}/notify", self.issue_id_or_key),
        );

        let body = match serde_json::to_value(&self.notification)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Returns either all transitions or a transition that can be performed by the user on an issue, based on the issue's status.
///
/// Note, if a request is made for a transition that does not exist or cannot be performed on the issue, given its status, the response will return any empty transitions list.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required: A list or transition is returned only when the user has:**
///
///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
///
/// However, if the user does not have the *Transition issues* [ project permission](https://confluence.atlassian.com/x/yodKLg) the response will not list any transitions.
pub struct GetTransitionsRequest<'a> {
    client: &'a crate::core::Client,
    issue_id_or_key: String,
    expand: Option<GetTransitionsRequestExpand>,
    transition_id: Option<String>,
    skip_remote_only_condition: Option<bool>,
    include_unavailable_transitions: Option<bool>,
    sort_by_ops_bar_and_status: Option<bool>,
}

impl<'a> GetTransitionsRequest<'a> {
    fn new(client: &'a crate::core::Client, issue_id_or_key: impl Into<String>) -> Self {
        Self {
            client,
            issue_id_or_key: issue_id_or_key.into(),
            expand: None,
            transition_id: None,
            skip_remote_only_condition: None,
            include_unavailable_transitions: None,
            sort_by_ops_bar_and_status: None,
        }
    }

    /// Use [expand](#expansion) to include additional information about transitions in the response. This parameter accepts `transitions.fields`, which returns information about the fields in the transition screen for each transition. Fields hidden from the screen are not returned. Use this information to populate the `fields` and `update` fields in [Transition issue](#api-rest-api-3-issue-issueIdOrKey-transitions-post).
    #[must_use]
    pub fn expand(mut self, value: GetTransitionsRequestExpand) -> Self {
        self.expand = Some(value);

        self
    }

    /// The ID of the transition.
    #[must_use]
    pub fn transition_id(mut self, value: impl Into<String>) -> Self {
        self.transition_id = Some(value.into());

        self
    }

    /// Whether transitions with the condition *Hide From User Condition* are included in the response. Available to Connect and Forge app users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) and Forge apps acting on behalf of users with *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    #[must_use]
    pub fn skip_remote_only_condition(mut self, value: bool) -> Self {
        self.skip_remote_only_condition = Some(value);

        self
    }

    /// Whether details of transitions that fail a condition are included in the response
    #[must_use]
    pub fn include_unavailable_transitions(mut self, value: bool) -> Self {
        self.include_unavailable_transitions = Some(value);

        self
    }

    /// Whether the transitions are sorted by ops-bar sequence value first then category order (Todo, In Progress, Done) or only by ops-bar sequence value.
    #[must_use]
    pub fn sort_by_ops_bar_and_status(mut self, value: bool) -> Self {
        self.sort_by_ops_bar_and_status = Some(value);

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::GET,
            format!("/rest/api/3/issue/{}/transitions", self.issue_id_or_key),
        );

        if let Some(value) = &self.expand {
            config.query.push(("expand".to_owned(), crate::core::QueryValue::from_serializable(value)?));
        }

        if let Some(value) = &self.transition_id {
            config.query.push(("transitionId".to_owned(), crate::core::QueryValue::Scalar(value.clone())));
        }

        if let Some(value) = &self.skip_remote_only_condition {
            config
                .query
                .push(("skipRemoteOnlyCondition".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.include_unavailable_transitions {
            config
                .query
                .push(("includeUnavailableTransitions".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.sort_by_ops_bar_and_status {
            config.query.push(("sortByOpsBarAndStatus".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<Transitions> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Performs an issue transition and, if the transition has a screen, updates the fields from the transition screen.
///
/// sortByCategory To update the fields on the transition screen, specify the fields in the `fields` or `update` parameters in the request body. Get details about the fields using [ Get transitions](#api-rest-api-3-issue-issueIdOrKey-transitions-get) with the `transitions.fields` expand.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse projects* and *Transition issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
pub struct DoTransitionRequest<'a> {
    client: &'a crate::core::Client,
    issue_id_or_key: String,
    issue_update_details: IssueUpdateDetails,
}

impl<'a> DoTransitionRequest<'a> {
    fn new(
        client: &'a crate::core::Client,
        issue_id_or_key: impl Into<String>,
        issue_update_details: IssueUpdateDetails,
    ) -> Self {
        Self { client, issue_id_or_key: issue_id_or_key.into(), issue_update_details }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::POST,
            format!("/rest/api/3/issue/{}/transitions", self.issue_id_or_key),
        );

        let body = match serde_json::to_value(&self.issue_update_details)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}
