// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::super::models::*;

/// The IssueCustomFieldValuesApps operations.
pub struct IssueCustomFieldValuesAppsService<'a> {
    client: &'a crate::core::Client,
}

impl<'a> IssueCustomFieldValuesAppsService<'a> {
    pub(crate) fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// Updates the value of one or more custom fields on one or more issues. Combinations of custom field and issue should be unique within the request.
    ///
    /// Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.
    ///
    /// **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.
    ///
    /// The new `write:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
    pub fn update_multiple_custom_field_values(
        &self,
        multiple_custom_field_values_update_details: MultipleCustomFieldValuesUpdateDetails,
    ) -> UpdateMultipleCustomFieldValuesRequest<'a> {
        UpdateMultipleCustomFieldValuesRequest::new(self.client, multiple_custom_field_values_update_details)
    }

    /// Updates the value of a custom field on one or more issues.
    ///
    /// Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.
    ///
    /// **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.
    ///
    /// The new `write:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
    pub fn update_custom_field_value(
        &self,
        field_id_or_key: impl Into<String>,
        custom_field_value_update_details: CustomFieldValueUpdateDetails,
    ) -> UpdateCustomFieldValueRequest<'a> {
        UpdateCustomFieldValueRequest::new(self.client, field_id_or_key, custom_field_value_update_details)
    }
}

/// Updates the value of one or more custom fields on one or more issues. Combinations of custom field and issue should be unique within the request.
///
/// Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.
///
/// **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.
///
/// The new `write:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
pub struct UpdateMultipleCustomFieldValuesRequest<'a> {
    client: &'a crate::core::Client,
    generate_changelog: Option<bool>,
    generate_app_events: Option<bool>,
    multiple_custom_field_values_update_details: MultipleCustomFieldValuesUpdateDetails,
}

impl<'a> UpdateMultipleCustomFieldValuesRequest<'a> {
    fn new(
        client: &'a crate::core::Client,
        multiple_custom_field_values_update_details: MultipleCustomFieldValuesUpdateDetails,
    ) -> Self {
        Self {
            client,
            multiple_custom_field_values_update_details,
            generate_changelog: None,
            generate_app_events: None,
        }
    }

    /// Whether to generate a changelog for this update.
    #[must_use]
    pub fn generate_changelog(mut self, value: bool) -> Self {
        self.generate_changelog = Some(value);

        self
    }

    /// Whether to generate app events for this update. Suppresses Forge, Connect, OAuth 2.0, and admin-configured webhooks (registered via the Jira admin UI). Note: Suppressing events means that "issue updated" events will not be emitted for your app or any other apps installed in Jira. This may cause other apps to retain stale data for the updated field, resulting in potentially confusing behaviour. We do not recommend using this flag in a Marketplace app as it may result in incompatibilities with other apps that depend on up-to-date issue data.
    #[must_use]
    pub fn generate_app_events(mut self, value: bool) -> Self {
        self.generate_app_events = Some(value);

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config =
            crate::core::RequestConfig::new(crate::core::Method::POST, "/rest/api/3/app/field/value".to_owned());

        if let Some(value) = &self.generate_changelog {
            config.query.push(("generateChangelog".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.generate_app_events {
            config.query.push(("generateAppEvents".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        let body = match serde_json::to_value(&self.multiple_custom_field_values_update_details)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Updates the value of a custom field on one or more issues.
///
/// Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.
///
/// **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.
///
/// The new `write:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
pub struct UpdateCustomFieldValueRequest<'a> {
    client: &'a crate::core::Client,
    field_id_or_key: String,
    generate_changelog: Option<bool>,
    generate_app_events: Option<bool>,
    custom_field_value_update_details: CustomFieldValueUpdateDetails,
}

impl<'a> UpdateCustomFieldValueRequest<'a> {
    fn new(
        client: &'a crate::core::Client,
        field_id_or_key: impl Into<String>,
        custom_field_value_update_details: CustomFieldValueUpdateDetails,
    ) -> Self {
        Self {
            client,
            field_id_or_key: field_id_or_key.into(),
            custom_field_value_update_details,
            generate_changelog: None,
            generate_app_events: None,
        }
    }

    /// Whether to generate a changelog for this update.
    #[must_use]
    pub fn generate_changelog(mut self, value: bool) -> Self {
        self.generate_changelog = Some(value);

        self
    }

    /// Whether to generate app events for this update. Suppresses Forge, Connect, OAuth 2.0, and admin-configured webhooks (registered via the Jira admin UI). Note: Suppressing events means that "issue updated" events will not be emitted for your app or any other apps installed in Jira. This may cause other apps to retain stale data for the updated field, resulting in potentially confusing behaviour. We do not recommend using this flag in a Marketplace app as it may result in incompatibilities with other apps that depend on up-to-date issue data.
    #[must_use]
    pub fn generate_app_events(mut self, value: bool) -> Self {
        self.generate_app_events = Some(value);

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::PUT,
            format!("/rest/api/3/app/field/{}/value", self.field_id_or_key),
        );

        if let Some(value) = &self.generate_changelog {
            config.query.push(("generateChangelog".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        if let Some(value) = &self.generate_app_events {
            config.query.push(("generateAppEvents".to_owned(), crate::core::QueryValue::Scalar(value.to_string())));
        }

        let body = match serde_json::to_value(&self.custom_field_value_update_details)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}
