// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::super::models::*;

/// The IssueLinks operations.
pub struct IssueLinksService<'a> {
    client: &'a crate::core::Client,
}

impl<'a> IssueLinksService<'a> {
    pub(crate) fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// Creates a link between two issues. Use this operation to indicate a relationship between two issues and optionally add a comment to the from (outward) issue. To use this resource the site must have [Issue Linking](https://confluence.atlassian.com/x/yoXKM) enabled.
    ///
    /// This resource returns nothing on the creation of an issue link. To obtain the ID of the issue link, use `https://your-domain.atlassian.net/rest/api/3/issue/[linked issue key]?fields=issuelinks`.
    ///
    /// If the link request duplicates a link, the response indicates that the issue link was created. If the request included a comment, the comment is added.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse project* [project permission](https://confluence.atlassian.com/x/yodKLg) for all the projects containing the issues to be linked,
    ///  *  *Link issues* [project permission](https://confluence.atlassian.com/x/yodKLg) on the project containing the from (outward) issue,
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
    ///  *  If the comment has visibility restrictions, belongs to the group or has the role visibility is restricted to.
    pub fn link_issues(&self, link_issue_request: LinkIssueRequest) -> LinkIssuesRequest<'a> {
        LinkIssuesRequest::new(self.client, link_issue_request)
    }

    /// Returns an issue link.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  *Browse project* [project permission](https://confluence.atlassian.com/x/yodKLg) for all the projects containing the linked issues.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, permission to view both of the issues.
    pub fn get_issue_link(&self, link_id: impl Into<String>) -> GetIssueLinkRequest<'a> {
        GetIssueLinkRequest::new(self.client, link_id)
    }

    /// Deletes an issue link.
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:**
    ///
    ///  *  Browse project [project permission](https://confluence.atlassian.com/x/yodKLg) for all the projects containing the issues in the link.
    ///  *  *Link issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for at least one of the projects containing issues in the link.
    ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, permission to view both of the issues.
    pub fn delete_issue_link(&self, link_id: impl Into<String>) -> DeleteIssueLinkRequest<'a> {
        DeleteIssueLinkRequest::new(self.client, link_id)
    }
}

/// Creates a link between two issues. Use this operation to indicate a relationship between two issues and optionally add a comment to the from (outward) issue. To use this resource the site must have [Issue Linking](https://confluence.atlassian.com/x/yoXKM) enabled.
///
/// This resource returns nothing on the creation of an issue link. To obtain the ID of the issue link, use `https://your-domain.atlassian.net/rest/api/3/issue/[linked issue key]?fields=issuelinks`.
///
/// If the link request duplicates a link, the response indicates that the issue link was created. If the request included a comment, the comment is added.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse project* [project permission](https://confluence.atlassian.com/x/yodKLg) for all the projects containing the issues to be linked,
///  *  *Link issues* [project permission](https://confluence.atlassian.com/x/yodKLg) on the project containing the from (outward) issue,
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
///  *  If the comment has visibility restrictions, belongs to the group or has the role visibility is restricted to.
pub struct LinkIssuesRequest<'a> {
    client: &'a crate::core::Client,
    link_issue_request: LinkIssueRequest,
}

impl<'a> LinkIssuesRequest<'a> {
    fn new(client: &'a crate::core::Client, link_issue_request: LinkIssueRequest) -> Self {
        Self { client, link_issue_request }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(crate::core::Method::POST, "/rest/api/3/issueLink".to_owned());

        let body = match serde_json::to_value(&self.link_issue_request)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Returns an issue link.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:**
///
///  *  *Browse project* [project permission](https://confluence.atlassian.com/x/yodKLg) for all the projects containing the linked issues.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, permission to view both of the issues.
pub struct GetIssueLinkRequest<'a> {
    client: &'a crate::core::Client,
    link_id: String,
}

impl<'a> GetIssueLinkRequest<'a> {
    fn new(client: &'a crate::core::Client, link_id: impl Into<String>) -> Self {
        Self { client, link_id: link_id.into() }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let config = crate::core::RequestConfig::new(
            crate::core::Method::GET,
            format!("/rest/api/3/issueLink/{}", self.link_id),
        );

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<IssueLink> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Deletes an issue link.
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:**
///
///  *  Browse project [project permission](https://confluence.atlassian.com/x/yodKLg) for all the projects containing the issues in the link.
///  *  *Link issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for at least one of the projects containing issues in the link.
///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, permission to view both of the issues.
pub struct DeleteIssueLinkRequest<'a> {
    client: &'a crate::core::Client,
    link_id: String,
}

impl<'a> DeleteIssueLinkRequest<'a> {
    fn new(client: &'a crate::core::Client, link_id: impl Into<String>) -> Self {
        Self { client, link_id: link_id.into() }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let config = crate::core::RequestConfig::new(
            crate::core::Method::DELETE,
            format!("/rest/api/3/issueLink/{}", self.link_id),
        );

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}
