// @generated. Do not edit: change the generator or the specification.

// A service takes its name from the tag the specification gave it, and one document names a
// tag after the surface itself.
#![allow(clippy::module_inception)]
#![allow(clippy::doc_lazy_continuation)]

mod announcement_banner;
mod api;
mod app_data_policies;
mod app_migration;
mod app_properties;
mod application_roles;
mod audit_records;
mod avatars;
mod dashboards;
mod dynamic_modules;
mod filter_sharing;
mod filters;
mod group_and_user_picker;
mod groups;
mod issue_attachments;
mod issue_bulk_operations;
mod issue_comment_properties;
mod issue_comments;
mod issue_custom_field_associations;
mod issue_custom_field_configuration_apps;
mod issue_custom_field_contexts;
mod issue_custom_field_options;
mod issue_custom_field_options_apps;
mod issue_custom_field_values_apps;
mod issue_fields;
mod issue_link_types;
mod issue_links;
mod issue_navigator_settings;
mod issue_notification_schemes;
mod issue_panels;
mod issue_priorities;
mod issue_properties;
mod issue_redaction;
mod issue_remote_links;
mod issue_resolutions;
mod issue_search;
mod issue_security_level;
mod issue_security_schemes;
mod issue_type_properties;
mod issue_type_schemes;
mod issue_type_screen_schemes;
mod issue_types;
mod issue_votes;
mod issue_watchers;
mod issue_worklog_properties;
mod issue_worklogs;
mod issues;
mod jira_expressions;
mod jira_settings;
mod jql;
mod jql_functions_apps;
mod labels;
mod migration_of_connect_modules_to_forge;
mod myself;
mod permission_schemes;
mod permissions;
mod project_avatars;
mod project_categories;
mod project_components;
mod project_email;
mod project_features;
mod project_key_and_name_validation;
mod project_permission_schemes;
mod project_properties;
mod project_role_actors;
mod project_roles;
mod project_templates;
mod project_types;
mod project_versions;
mod projects;
mod screen_schemes;
mod screen_tab_fields;
mod screen_tabs;
mod screens;
mod server_info;
mod status;
mod tasks;
mod time_tracking;
mod ui_modifications_apps;
mod user_properties;
mod user_search;
mod users;
mod webhooks;
mod workflow_scheme_drafts;
mod workflow_scheme_project_associations;
mod workflow_schemes;
mod workflow_status_categories;
mod workflow_statuses;
mod workflow_transition_rules;
mod workflows;

pub use announcement_banner::*;
pub use api::*;
pub use app_data_policies::*;
pub use app_migration::*;
pub use app_properties::*;
pub use application_roles::*;
pub use audit_records::*;
pub use avatars::*;
pub use dashboards::*;
pub use dynamic_modules::*;
pub use filter_sharing::*;
pub use filters::*;
pub use group_and_user_picker::*;
pub use groups::*;
pub use issue_attachments::*;
pub use issue_bulk_operations::*;
pub use issue_comment_properties::*;
pub use issue_comments::*;
pub use issue_custom_field_associations::*;
pub use issue_custom_field_configuration_apps::*;
pub use issue_custom_field_contexts::*;
pub use issue_custom_field_options::*;
pub use issue_custom_field_options_apps::*;
pub use issue_custom_field_values_apps::*;
pub use issue_fields::*;
pub use issue_link_types::*;
pub use issue_links::*;
pub use issue_navigator_settings::*;
pub use issue_notification_schemes::*;
pub use issue_panels::*;
pub use issue_priorities::*;
pub use issue_properties::*;
pub use issue_redaction::*;
pub use issue_remote_links::*;
pub use issue_resolutions::*;
pub use issue_search::*;
pub use issue_security_level::*;
pub use issue_security_schemes::*;
pub use issue_type_properties::*;
pub use issue_type_schemes::*;
pub use issue_type_screen_schemes::*;
pub use issue_types::*;
pub use issue_votes::*;
pub use issue_watchers::*;
pub use issue_worklog_properties::*;
pub use issue_worklogs::*;
pub use issues::*;
pub use jira_expressions::*;
pub use jira_settings::*;
pub use jql::*;
pub use jql_functions_apps::*;
pub use labels::*;
pub use migration_of_connect_modules_to_forge::*;
pub use myself::*;
pub use permission_schemes::*;
pub use permissions::*;
pub use project_avatars::*;
pub use project_categories::*;
pub use project_components::*;
pub use project_email::*;
pub use project_features::*;
pub use project_key_and_name_validation::*;
pub use project_permission_schemes::*;
pub use project_properties::*;
pub use project_role_actors::*;
pub use project_roles::*;
pub use project_templates::*;
pub use project_types::*;
pub use project_versions::*;
pub use projects::*;
pub use screen_schemes::*;
pub use screen_tab_fields::*;
pub use screen_tabs::*;
pub use screens::*;
pub use server_info::*;
pub use status::*;
pub use tasks::*;
pub use time_tracking::*;
pub use ui_modifications_apps::*;
pub use user_properties::*;
pub use user_search::*;
pub use users::*;
pub use webhooks::*;
pub use workflow_scheme_drafts::*;
pub use workflow_scheme_project_associations::*;
pub use workflow_schemes::*;
pub use workflow_status_categories::*;
pub use workflow_statuses::*;
pub use workflow_transition_rules::*;
pub use workflows::*;
