// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::super::models::*;

/// The ProjectTemplates operations.
pub struct ProjectTemplatesService<'a> {
    client: &'a crate::core::Client,
}

impl<'a> ProjectTemplatesService<'a> {
    pub(crate) fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// Creates a project based on a custom template provided in the request.
    ///
    /// The request body should contain the project details and the capabilities that comprise the project:
    ///
    ///  *  `details` \- represents the project details settings
    ///  *  `template` \- represents a list of capabilities responsible for creating specific parts of a project
    ///
    /// A capability is defined as a unit of configuration for the project you want to create.
    ///
    /// This operation is:
    ///
    ///  *  [asynchronous](#async). Follow the `Location` link in the response header to determine the status of the task and use [Get task](#api-rest-api-3-task-taskId-get) to obtain subsequent updates.
    ///
    /// ***Note: This API is only supported for Jira Enterprise edition.***
    ///
    /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    pub fn create_project_with_custom_template(
        &self,
        project_custom_template_create_request_dto: ProjectCustomTemplateCreateRequestDTO,
    ) -> CreateProjectWithCustomTemplateRequest<'a> {
        CreateProjectWithCustomTemplateRequest::new(self.client, project_custom_template_create_request_dto)
    }
}

/// Creates a project based on a custom template provided in the request.
///
/// The request body should contain the project details and the capabilities that comprise the project:
///
///  *  `details` \- represents the project details settings
///  *  `template` \- represents a list of capabilities responsible for creating specific parts of a project
///
/// A capability is defined as a unit of configuration for the project you want to create.
///
/// This operation is:
///
///  *  [asynchronous](#async). Follow the `Location` link in the response header to determine the status of the task and use [Get task](#api-rest-api-3-task-taskId-get) to obtain subsequent updates.
///
/// ***Note: This API is only supported for Jira Enterprise edition.***
///
/// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
pub struct CreateProjectWithCustomTemplateRequest<'a> {
    client: &'a crate::core::Client,
    project_custom_template_create_request_dto: ProjectCustomTemplateCreateRequestDTO,
}

impl<'a> CreateProjectWithCustomTemplateRequest<'a> {
    fn new(
        client: &'a crate::core::Client,
        project_custom_template_create_request_dto: ProjectCustomTemplateCreateRequestDTO,
    ) -> Self {
        Self { client, project_custom_template_create_request_dto }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config =
            crate::core::RequestConfig::new(crate::core::Method::POST, "/rest/api/3/project-template".to_owned());

        let body = match serde_json::to_value(&self.project_custom_template_create_request_dto)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}
