// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::super::models::*;

/// The ProjectRoleActors operations.
pub struct ProjectRoleActorsService<'a> {
    client: &'a crate::core::Client,
}

impl<'a> ProjectRoleActorsService<'a> {
    pub(crate) fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// Adds actors to a project role for the project.
    ///
    /// To replace all actors for the project, use [Set actors for project role](#api-rest-api-3-project-projectIdOrKey-role-id-put).
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    pub fn add_actor_users(
        &self,
        project_id_or_key: impl Into<String>,
        id: i64,
        actors_map: ActorsMap,
    ) -> AddActorUsersRequest<'a> {
        AddActorUsersRequest::new(self.client, project_id_or_key, id, actors_map)
    }

    /// Sets the actors for a project role for a project, replacing all existing actors.
    ///
    /// To add actors to the project without overwriting the existing list, use [Add actors to project role](#api-rest-api-3-project-projectIdOrKey-role-id-post).
    ///
    /// **[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    pub fn set_actors(
        &self,
        project_id_or_key: impl Into<String>,
        id: i64,
        body: ProjectRoleActorsUpdate,
    ) -> SetActorsRequest<'a> {
        SetActorsRequest::new(self.client, project_id_or_key, id, body)
    }

    /// Deletes actors from a project role for the project.
    ///
    /// To remove default actors from the project role, use [Delete default actors from project role](#api-rest-api-3-role-id-actors-delete).
    ///
    /// This operation can be accessed anonymously.
    ///
    /// **[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    pub fn delete_actor(&self, project_id_or_key: impl Into<String>, id: i64) -> DeleteActorRequest<'a> {
        DeleteActorRequest::new(self.client, project_id_or_key, id)
    }

    /// Returns the [default actors](#api-rest-api-3-resolution-get) for the project role.
    ///
    /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    pub fn get_project_role_actors_for_role(&self, id: i64) -> GetProjectRoleActorsForRoleRequest<'a> {
        GetProjectRoleActorsForRoleRequest::new(self.client, id)
    }

    /// Adds [default actors](#api-rest-api-3-resolution-get) to a role. You may add groups or users, but you cannot add groups and users in the same request.
    ///
    /// Changing a project role's default actors does not affect project role members for projects already created.
    ///
    /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    pub fn add_project_role_actors_to_role(
        &self,
        id: i64,
        actor_input: ActorInput,
    ) -> AddProjectRoleActorsToRoleRequest<'a> {
        AddProjectRoleActorsToRoleRequest::new(self.client, id, actor_input)
    }

    /// Deletes the [default actors](#api-rest-api-3-resolution-get) from a project role. You may delete a group or user, but you cannot delete a group and a user in the same request.
    ///
    /// Changing a project role's default actors does not affect project role members for projects already created.
    ///
    /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
    pub fn delete_project_role_actors_from_role(&self, id: i64) -> DeleteProjectRoleActorsFromRoleRequest<'a> {
        DeleteProjectRoleActorsFromRoleRequest::new(self.client, id)
    }
}

/// Adds actors to a project role for the project.
///
/// To replace all actors for the project, use [Set actors for project role](#api-rest-api-3-project-projectIdOrKey-role-id-put).
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
pub struct AddActorUsersRequest<'a> {
    client: &'a crate::core::Client,
    project_id_or_key: String,
    id: i64,
    actors_map: ActorsMap,
}

impl<'a> AddActorUsersRequest<'a> {
    fn new(
        client: &'a crate::core::Client,
        project_id_or_key: impl Into<String>,
        id: i64,
        actors_map: ActorsMap,
    ) -> Self {
        Self {
            client,
            project_id_or_key: project_id_or_key.into(),
            id,
            actors_map,
        }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::POST,
            format!("/rest/api/3/project/{}/role/{}", self.project_id_or_key, self.id),
        );

        let body = match serde_json::to_value(&self.actors_map)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<ProjectRole> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Sets the actors for a project role for a project, replacing all existing actors.
///
/// To add actors to the project without overwriting the existing list, use [Add actors to project role](#api-rest-api-3-project-projectIdOrKey-role-id-post).
///
/// **[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
pub struct SetActorsRequest<'a> {
    client: &'a crate::core::Client,
    project_id_or_key: String,
    id: i64,
    body: ProjectRoleActorsUpdate,
}

impl<'a> SetActorsRequest<'a> {
    fn new(
        client: &'a crate::core::Client,
        project_id_or_key: impl Into<String>,
        id: i64,
        body: ProjectRoleActorsUpdate,
    ) -> Self {
        Self {
            client,
            project_id_or_key: project_id_or_key.into(),
            id,
            body,
        }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::PUT,
            format!("/rest/api/3/project/{}/role/{}", self.project_id_or_key, self.id),
        );

        config.body = Some(crate::core::Body::Json(serde_json::to_value(&self.body)?));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<ProjectRole> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Deletes actors from a project role for the project.
///
/// To remove default actors from the project role, use [Delete default actors from project role](#api-rest-api-3-role-id-actors-delete).
///
/// This operation can be accessed anonymously.
///
/// **[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
pub struct DeleteActorRequest<'a> {
    client: &'a crate::core::Client,
    project_id_or_key: String,
    id: i64,
    user: Option<String>,
    group: Option<String>,
    group_id: Option<String>,
}

impl<'a> DeleteActorRequest<'a> {
    fn new(client: &'a crate::core::Client, project_id_or_key: impl Into<String>, id: i64) -> Self {
        Self {
            client,
            project_id_or_key: project_id_or_key.into(),
            id,
            user: None,
            group: None,
            group_id: None,
        }
    }

    /// The user account ID of the user to remove from the project role.
    #[must_use]
    pub fn user(mut self, value: impl Into<String>) -> Self {
        self.user = Some(value.into());

        self
    }

    /// The name of the group to remove from the project role. This parameter cannot be used with the `groupId` parameter. As a group's name can change, use of `groupId` is recommended.
    #[must_use]
    pub fn group(mut self, value: impl Into<String>) -> Self {
        self.group = Some(value.into());

        self
    }

    /// The ID of the group to remove from the project role. This parameter cannot be used with the `group` parameter.
    #[must_use]
    pub fn group_id(mut self, value: impl Into<String>) -> Self {
        self.group_id = Some(value.into());

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::DELETE,
            format!("/rest/api/3/project/{}/role/{}", self.project_id_or_key, self.id),
        );

        if let Some(value) = &self.user {
            config
                .query
                .push(("user".to_owned(), crate::core::QueryValue::Scalar(value.clone())));
        }

        if let Some(value) = &self.group {
            config
                .query
                .push(("group".to_owned(), crate::core::QueryValue::Scalar(value.clone())));
        }

        if let Some(value) = &self.group_id {
            config
                .query
                .push(("groupId".to_owned(), crate::core::QueryValue::Scalar(value.clone())));
        }

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Returns the [default actors](#api-rest-api-3-resolution-get) for the project role.
///
/// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
pub struct GetProjectRoleActorsForRoleRequest<'a> {
    client: &'a crate::core::Client,
    id: i64,
}

impl<'a> GetProjectRoleActorsForRoleRequest<'a> {
    fn new(client: &'a crate::core::Client, id: i64) -> Self {
        Self { client, id }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let config =
            crate::core::RequestConfig::new(crate::core::Method::GET, format!("/rest/api/3/role/{}/actors", self.id));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<ProjectRole> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Adds [default actors](#api-rest-api-3-resolution-get) to a role. You may add groups or users, but you cannot add groups and users in the same request.
///
/// Changing a project role's default actors does not affect project role members for projects already created.
///
/// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
pub struct AddProjectRoleActorsToRoleRequest<'a> {
    client: &'a crate::core::Client,
    id: i64,
    actor_input: ActorInput,
}

impl<'a> AddProjectRoleActorsToRoleRequest<'a> {
    fn new(client: &'a crate::core::Client, id: i64, actor_input: ActorInput) -> Self {
        Self {
            client,
            id,
            actor_input,
        }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::POST,
            format!("/rest/api/3/role/{}/actors", self.id),
        );

        let body = match serde_json::to_value(&self.actor_input)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<ProjectRole> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Deletes the [default actors](#api-rest-api-3-resolution-get) from a project role. You may delete a group or user, but you cannot delete a group and a user in the same request.
///
/// Changing a project role's default actors does not affect project role members for projects already created.
///
/// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
pub struct DeleteProjectRoleActorsFromRoleRequest<'a> {
    client: &'a crate::core::Client,
    id: i64,
    user: Option<String>,
    group_id: Option<String>,
    group: Option<String>,
}

impl<'a> DeleteProjectRoleActorsFromRoleRequest<'a> {
    fn new(client: &'a crate::core::Client, id: i64) -> Self {
        Self {
            client,
            id,
            user: None,
            group_id: None,
            group: None,
        }
    }

    /// The user account ID of the user to remove as a default actor.
    #[must_use]
    pub fn user(mut self, value: impl Into<String>) -> Self {
        self.user = Some(value.into());

        self
    }

    /// The group ID of the group to be removed as a default actor. This parameter cannot be used with the `group` parameter.
    #[must_use]
    pub fn group_id(mut self, value: impl Into<String>) -> Self {
        self.group_id = Some(value.into());

        self
    }

    /// The group name of the group to be removed as a default actor.This parameter cannot be used with the `groupId` parameter. As a group's name can change, use of `groupId` is recommended.
    #[must_use]
    pub fn group(mut self, value: impl Into<String>) -> Self {
        self.group = Some(value.into());

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::DELETE,
            format!("/rest/api/3/role/{}/actors", self.id),
        );

        if let Some(value) = &self.user {
            config
                .query
                .push(("user".to_owned(), crate::core::QueryValue::Scalar(value.clone())));
        }

        if let Some(value) = &self.group_id {
            config
                .query
                .push(("groupId".to_owned(), crate::core::QueryValue::Scalar(value.clone())));
        }

        if let Some(value) = &self.group {
            config
                .query
                .push(("group".to_owned(), crate::core::QueryValue::Scalar(value.clone())));
        }

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<ProjectRole> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}
