// @generated by apis-code-gen. Do not edit: change the generator or the specification.

// A service takes its name from the tag the specification gave it, and one document names a
// tag after the surface itself.
#![allow(clippy::module_inception)]
#![allow(clippy::doc_lazy_continuation)]

mod approvals;
mod customer_requests;
mod customer_transitions;
mod customers;
mod info;
mod organizations;
mod portals;
mod queue_settings;
mod queues;
mod request_attachments;
mod request_type_permissions;
mod request_types;
mod service_desk_organizations;
mod service_desks;

pub use approvals::*;
pub use customer_requests::*;
pub use customer_transitions::*;
pub use customers::*;
pub use info::*;
pub use organizations::*;
pub use portals::*;
pub use queue_settings::*;
pub use queues::*;
pub use request_attachments::*;
pub use request_type_permissions::*;
pub use request_types::*;
pub use service_desk_organizations::*;
pub use service_desks::*;
