// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::super::models::*;

/// The ObjectAttributes operations.
pub struct ObjectAttributesService<'a> {
    client: &'a crate::core::Client,
}

impl<'a> ObjectAttributesService<'a> {
    pub(crate) fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// Create a new attribute for a given object.
    pub fn create_object_attribute(&self) -> CreateObjectAttributeRequest<'a> {
        CreateObjectAttributeRequest::new(self.client)
    }
}

/// Create a new attribute for a given object.
pub struct CreateObjectAttributeRequest<'a> {
    client: &'a crate::core::Client,
    include_type_attribute: Option<String>,
    object_attribute_in: Option<ObjectAttributeIn>,
}

impl<'a> CreateObjectAttributeRequest<'a> {
    fn new(client: &'a crate::core::Client) -> Self {
        Self { client, include_type_attribute: None, object_attribute_in: None }
    }

    /// Should the response include the object type attribute definition
    #[must_use]
    pub fn include_type_attribute(mut self, value: impl Into<String>) -> Self {
        self.include_type_attribute = Some(value.into());

        self
    }

    #[must_use]
    pub fn object_attribute_in(mut self, value: ObjectAttributeIn) -> Self {
        self.object_attribute_in = Some(value);

        self
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(
            crate::core::Method::POST,
            "/rest/assets/1.0/objectattribute/create".to_owned(),
        );

        if let Some(value) = &self.include_type_attribute {
            config.query.push(("includeTypeAttribute".to_owned(), crate::core::QueryValue::Scalar(value.clone())));
        }

        let body = match serde_json::to_value(&self.object_attribute_in)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<ObjectAttribute> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}
