// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MembershipFetchPayload {
    /// Pagination cursor, only members after the cursor will be returned
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
    /// Maximum number of members to be returned
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first: Option<i64>,
}
