// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

crate::open_enum! {
    pub enum BadRequestExceptionResponseStatus {
        OK => "OK",
        CREATED => "CREATED",
        ACCEPTED => "ACCEPTED",
        NOCONTENT => "NO_CONTENT",
        RESETCONTENT => "RESET_CONTENT",
        PARTIALCONTENT => "PARTIAL_CONTENT",
        MOVEDPERMANENTLY => "MOVED_PERMANENTLY",
        FOUND => "FOUND",
        SEEOTHER => "SEE_OTHER",
        NOTMODIFIED => "NOT_MODIFIED",
        USEPROXY => "USE_PROXY",
        TEMPORARYREDIRECT => "TEMPORARY_REDIRECT",
        BADREQUEST => "BAD_REQUEST",
        UNAUTHORIZED => "UNAUTHORIZED",
        PAYMENTREQUIRED => "PAYMENT_REQUIRED",
        FORBIDDEN => "FORBIDDEN",
        NOTFOUND => "NOT_FOUND",
        METHODNOTALLOWED => "METHOD_NOT_ALLOWED",
        NOTACCEPTABLE => "NOT_ACCEPTABLE",
        PROXYAUTHENTICATIONREQUIRED => "PROXY_AUTHENTICATION_REQUIRED",
        REQUESTTIMEOUT => "REQUEST_TIMEOUT",
        CONFLICT => "CONFLICT",
        GONE => "GONE",
        LENGTHREQUIRED => "LENGTH_REQUIRED",
        PRECONDITIONFAILED => "PRECONDITION_FAILED",
        REQUESTENTITYTOOLARGE => "REQUEST_ENTITY_TOO_LARGE",
        REQUESTURITOOLONG => "REQUEST_URI_TOO_LONG",
        UNSUPPORTEDMEDIATYPE => "UNSUPPORTED_MEDIA_TYPE",
        REQUESTEDRANGENOTSATISFIABLE => "REQUESTED_RANGE_NOT_SATISFIABLE",
        EXPECTATIONFAILED => "EXPECTATION_FAILED",
        INTERNALSERVERERROR => "INTERNAL_SERVER_ERROR",
        NOTIMPLEMENTED => "NOT_IMPLEMENTED",
        BADGATEWAY => "BAD_GATEWAY",
        SERVICEUNAVAILABLE => "SERVICE_UNAVAILABLE",
        GATEWAYTIMEOUT => "GATEWAY_TIMEOUT",
        HTTPVERSIONNOTSUPPORTED => "HTTP_VERSION_NOT_SUPPORTED",
    }
}

crate::open_enum! {
    pub enum BadRequestExceptionScimErrorType {
        InvalidFilter => "invalidFilter",
        TooMany => "tooMany",
        Uniqueness => "uniqueness",
        Mutability => "mutability",
        InvalidSyntax => "invalidSyntax",
        InvalidPath => "invalidPath",
        NoTarget => "noTarget",
        InvalidValue => "invalidValue",
        InvalidVers => "invalidVers",
        Sensitive => "sensitive",
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BadRequestException {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cause: Option<Box<Throwable>>,
    #[serde(rename = "stackTrace", default, skip_serializing_if = "Option::is_none")]
    pub stack_trace: Option<Vec<StackTraceElement>>,
    #[serde(rename = "responseStatus", default, skip_serializing_if = "Option::is_none")]
    pub response_status: Option<BadRequestExceptionResponseStatus>,
    #[serde(rename = "scimErrorType", default, skip_serializing_if = "Option::is_none")]
    pub scim_error_type: Option<BadRequestExceptionScimErrorType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "localizedMessage", default, skip_serializing_if = "Option::is_none")]
    pub localized_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub suppressed: Option<Vec<Box<Throwable>>>,
}
