// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ProxyError {
    /// The HTTP status code applicable to this error.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<f64>,
    /// Human-readable explanation of the error.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}
