// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RoleIdCounts {
    /// The ID of the role.
    #[serde(rename = "roleId", default, skip_serializing_if = "Option::is_none")]
    pub role_id: Option<String>,
    /// The number of users with this role.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}
