// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomTemplateOptions {
    /// Enable screen delegated admin support for the template. This means screen and associated schemes will be copied rather than referenced.
    #[serde(rename = "enableScreenDelegatedAdminSupport", default, skip_serializing_if = "Option::is_none")]
    pub enable_screen_delegated_admin_support: Option<bool>,
    /// Enable workflow delegated admin support for the template. This means workflows and workflow schemes will be copied rather than referenced.
    #[serde(rename = "enableWorkflowDelegatedAdminSupport", default, skip_serializing_if = "Option::is_none")]
    pub enable_workflow_delegated_admin_support: Option<bool>,
}
