// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

crate::open_enum! {
    /// The scope of the default sharing for new filters and dashboards:
    ///
    ///  *  `AUTHENTICATED` Shared with all logged-in users.
    ///  *  `GLOBAL` Shared with all logged-in users. This shows as `AUTHENTICATED` in the response.
    ///  *  `PRIVATE` Not shared with any users.
    pub enum DefaultShareScopeScope {
        GLOBAL => "GLOBAL",
        AUTHENTICATED => "AUTHENTICATED",
        PRIVATE => "PRIVATE",
    }
}

/// Details of the scope of the default sharing for new filters and dashboards.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DefaultShareScope {
    /// The scope of the default sharing for new filters and dashboards:
    ///
    ///  *  `AUTHENTICATED` Shared with all logged-in users.
    ///  *  `GLOBAL` Shared with all logged-in users. This shows as `AUTHENTICATED` in the response.
    ///  *  `PRIVATE` Not shared with any users.
    pub scope: DefaultShareScopeScope,
}
