// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

/// A paginated list of subscriptions to a filter.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FilterSubscriptionsList {
    /// The index of the last item returned on the page.
    #[serde(rename = "end-index", default, skip_serializing_if = "Option::is_none")]
    pub end_index: Option<i64>,
    /// The list of items.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<FilterSubscription>>,
    /// The maximum number of results that could be on the page.
    #[serde(rename = "max-results", default, skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i64>,
    /// The number of items on the page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    /// The index of the first item returned on the page.
    #[serde(rename = "start-index", default, skip_serializing_if = "Option::is_none")]
    pub start_index: Option<i64>,
}
