// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

/// Details about a filter.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Filter {
    /// \[Experimental\] Approximate last used time. Returns the date and time when the filter was last used. Returns `null` if the filter hasn't been used after tracking was enabled. For performance reasons, timestamps aren't updated in real time and therefore may not be exactly accurate.
    #[serde(rename = "approximateLastUsed", default, skip_serializing_if = "Option::is_none")]
    pub approximate_last_used: Option<String>,
    /// A description of the filter.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The groups and projects that can edit the filter.
    #[serde(rename = "editPermissions", default, skip_serializing_if = "Option::is_none")]
    pub edit_permissions: Option<Vec<SharePermission>>,
    /// Whether the filter is selected as a favorite.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub favourite: Option<bool>,
    /// The count of how many users have selected this filter as a favorite, including the filter owner.
    #[serde(rename = "favouritedCount", default, skip_serializing_if = "Option::is_none")]
    pub favourited_count: Option<i64>,
    /// The unique identifier for the filter.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The JQL query for the filter. For example, *project = SSP AND issuetype = Bug*.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub jql: Option<String>,
    /// The name of the filter. Must be unique.
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub owner: Option<DashboardUser>,
    /// A URL to view the filter results in Jira, using the [Search for issues using JQL](#api-rest-api-3-filter-search-get) operation with the filter's JQL string to return the filter results. For example, *https://your-domain.atlassian.net/rest/api/3/search?jql=project+%3D+SSP+AND+issuetype+%3D+Bug*.
    #[serde(rename = "searchUrl", default, skip_serializing_if = "Option::is_none")]
    pub search_url: Option<String>,
    /// The URL of the filter.
    #[serde(rename = "self", default, skip_serializing_if = "Option::is_none")]
    pub self_: Option<String>,
    /// The groups and projects that the filter is shared with.
    #[serde(rename = "sharePermissions", default, skip_serializing_if = "Option::is_none")]
    pub share_permissions: Option<Vec<SharePermission>>,
    #[serde(rename = "sharedUsers", default, skip_serializing_if = "Option::is_none")]
    pub shared_users: Option<UserList>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<FilterSubscriptionsList>,
    /// A URL to view the filter results in Jira, using the ID of the filter. For example, *https://your-domain.atlassian.net/issues/?filter=10100*.
    #[serde(rename = "viewUrl", default, skip_serializing_if = "Option::is_none")]
    pub view_url: Option<String>,
    #[serde(rename = "isWritable", default, skip_serializing_if = "Option::is_none")]
    pub is_writable: Option<bool>,
}
