// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

/// The wrapper for the issue creation metadata for a list of projects.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IssueCreateMetadata {
    /// Expand options that include additional project details in the response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expand: Option<String>,
    /// List of projects and their issue creation metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub projects: Option<Vec<ProjectIssueCreateMetadata>>,
}
