// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

/// Issue security level member.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IssueSecurityLevelMember {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub holder: Option<PermissionHolder>,
    /// The ID of the issue security level member.
    pub id: i64,
    /// The ID of the issue security level.
    #[serde(rename = "issueSecurityLevelId")]
    pub issue_security_level_id: i64,
}
