// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

/// The ID of an issue type screen scheme.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IssueTypeScreenSchemeId {
    /// The ID of the issue type screen scheme.
    pub id: String,
}
