// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct JiraDurationField {
    #[serde(rename = "originalEstimateField")]
    pub original_estimate_field: String,
}
