// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JiraRichTextField {
    #[serde(rename = "fieldId")]
    pub field_id: String,
    #[serde(rename = "richText")]
    pub rich_text: JiraRichTextInput,
}
