// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

/// Details of an operand in a JQL clause.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
#[allow(clippy::large_enum_variant)]
pub enum JqlQueryClauseOperand {
    ListOperand(ListOperand),
    ValueOperand(ValueOperand),
    FunctionOperand(FunctionOperand),
    KeywordOperand(KeywordOperand),
}
