// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

/// The JQL query to sanitize for the account ID. If the account ID is null, sanitizing is performed for an anonymous user.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct JqlQueryToSanitize {
    /// The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*.
    #[serde(rename = "accountId", default, skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// The query to sanitize.
    pub query: String,
}
