// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

/// Details about a license for the Jira instance.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct License {
    /// The applications under this license.
    pub applications: Vec<LicensedApplication>,
}
