// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

/// The ID of a screen scheme.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ScreenSchemeId {
    /// The ID of the screen scheme.
    pub id: i64,
}
