// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

/// Experimental. A warning returned alongside successful search results.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchWarning {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<SearchWarningLimitDetails>,
    /// A human-readable explanation of the warning suitable for surfacing to end users.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The type of warning, e.g. CLAUSE\_LIMIT\_EXCEEDED.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}
