// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

/// Result for requested redactions
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SingleRedactionResponse {
    /// An unique id for the redaction request
    #[serde(rename = "externalId")]
    pub external_id: String,
    /// Indicates if redaction was success/failure
    pub successful: bool,
}
