// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

crate::open_enum! {
    /// The scope of the status. `GLOBAL` for company-managed projects and `PROJECT` for team-managed projects.
    pub enum StatusScopeType {
        PROJECT => "PROJECT",
        GLOBAL => "GLOBAL",
    }
}

/// The scope of the status.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StatusScope {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project: Option<ProjectId>,
    /// The scope of the status. `GLOBAL` for company-managed projects and `PROJECT` for team-managed projects.
    pub r#type: StatusScopeType,
}
