// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

/// An issue suggested for use in the issue picker auto-completion.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SuggestedIssue {
    /// The ID of the issue.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// The URL of the issue type's avatar.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub img: Option<String>,
    /// The key of the issue.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The key of the issue in HTML format.
    #[serde(rename = "keyHtml", default, skip_serializing_if = "Option::is_none")]
    pub key_html: Option<String>,
    /// The phrase containing the query string in HTML format, with the string highlighted with HTML bold tags.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// The phrase containing the query string, as plain text.
    #[serde(rename = "summaryText", default, skip_serializing_if = "Option::is_none")]
    pub summary_text: Option<String>,
}
