// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

/// The statuses the transition can start from, and the mapping of ports between the statuses.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct WorkflowTransitionLinks {
    /// The port that the transition starts from.
    #[serde(rename = "fromPort", default, skip_serializing_if = "Option::is_none")]
    pub from_port: Option<i64>,
    /// The status that the transition starts from.
    #[serde(rename = "fromStatusReference", default, skip_serializing_if = "Option::is_none")]
    pub from_status_reference: Option<String>,
    /// The port that the transition goes to.
    #[serde(rename = "toPort", default, skip_serializing_if = "Option::is_none")]
    pub to_port: Option<i64>,
}
