// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

/// The details of the workflows to update.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowUpdate {
    /// The mapping of old to new status ID.
    #[serde(rename = "defaultStatusMappings", default, skip_serializing_if = "Option::is_none")]
    pub default_status_mappings: Option<Vec<StatusMigration>>,
    /// The new description for this workflow.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The ID of this workflow.
    pub id: String,
    #[serde(rename = "loopedTransitionContainerLayout", default, skip_serializing_if = "Option::is_none")]
    pub looped_transition_container_layout: Option<WorkflowLayout>,
    #[serde(rename = "startPointLayout", default, skip_serializing_if = "Option::is_none")]
    pub start_point_layout: Option<WorkflowLayout>,
    /// The mapping of old to new status ID for a specific project and issue type.
    #[serde(rename = "statusMappings", default, skip_serializing_if = "Option::is_none")]
    pub status_mappings: Option<Vec<StatusMappingDTO>>,
    /// The statuses associated with this workflow.
    pub statuses: Vec<StatusLayoutUpdate>,
    /// The transitions of this workflow.
    pub transitions: Vec<TransitionUpdateDTO>,
    pub version: DocumentVersion,
    /// Keys the specification does not describe, kept rather than dropped.
    #[serde(flatten)]
    pub additional: std::collections::HashMap<String, serde_json::Value>,
}
