// @generated. Do not edit: change the generator or the specification.

// A service takes its name from the tag the specification gave it, and one document names a
// tag after the surface itself.
#![allow(clippy::module_inception)]
#![allow(clippy::doc_lazy_continuation)]

mod application_properties;
mod application_roles;
mod avatars;
mod backlog;
mod board;
mod cluster;
mod configuration;
mod dashboards;
mod email_templates;
mod epic;
mod filters;
mod group_and_user_picker;
mod groups;
mod indexing;
mod issue_attachments;
mod issue_comments;
mod issue_custom_field_options;
mod issue_fields;
mod issue_link_types;
mod issue_links;
mod issue_notification_schemes;
mod issue_priorities;
mod issue_resolutions;
mod issue_search;
mod issue_security_level;
mod issue_security_schemes;
mod issue_type_schemes;
mod issue_types;
mod issue_worklogs;
mod issues;
mod jira_settings;
mod jql;
mod license_validator;
mod monitoring;
mod my_preferences;
mod myself;
mod password;
mod permission_schemes;
mod permissions;
mod priority_schemes;
mod project_categories;
mod project_components;
mod project_key_and_name_validation;
mod project_roles;
mod project_versions;
mod projects;
mod read_only_mode;
mod screens;
mod search_limits;
mod server_info;
mod session;
mod sprint;
mod terminology;
mod upgrade;
mod users;
mod webhooks;
mod websudo;
mod workflow_schemes;
mod workflow_status_categories;
mod workflow_statuses;
mod workflows;

pub use application_properties::*;
pub use application_roles::*;
pub use avatars::*;
pub use backlog::*;
pub use board::*;
pub use cluster::*;
pub use configuration::*;
pub use dashboards::*;
pub use email_templates::*;
pub use epic::*;
pub use filters::*;
pub use group_and_user_picker::*;
pub use groups::*;
pub use indexing::*;
pub use issue_attachments::*;
pub use issue_comments::*;
pub use issue_custom_field_options::*;
pub use issue_fields::*;
pub use issue_link_types::*;
pub use issue_links::*;
pub use issue_notification_schemes::*;
pub use issue_priorities::*;
pub use issue_resolutions::*;
pub use issue_search::*;
pub use issue_security_level::*;
pub use issue_security_schemes::*;
pub use issue_type_schemes::*;
pub use issue_types::*;
pub use issue_worklogs::*;
pub use issues::*;
pub use jira_settings::*;
pub use jql::*;
pub use license_validator::*;
pub use monitoring::*;
pub use my_preferences::*;
pub use myself::*;
pub use password::*;
pub use permission_schemes::*;
pub use permissions::*;
pub use priority_schemes::*;
pub use project_categories::*;
pub use project_components::*;
pub use project_key_and_name_validation::*;
pub use project_roles::*;
pub use project_versions::*;
pub use projects::*;
pub use read_only_mode::*;
pub use screens::*;
pub use search_limits::*;
pub use server_info::*;
pub use session::*;
pub use sprint::*;
pub use terminology::*;
pub use upgrade::*;
pub use users::*;
pub use webhooks::*;
pub use websudo::*;
pub use workflow_schemes::*;
pub use workflow_status_categories::*;
pub use workflow_statuses::*;
pub use workflows::*;
