// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::super::models::*;

/// The Session operations.
pub struct SessionService<'a> {
    client: &'a crate::core::Client,
}

impl<'a> SessionService<'a> {
    pub(crate) fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// Returns information about the currently authenticated user's session. If the caller is not authenticated they will get a 401 Unauthorized status code.
    pub fn current_user(&self) -> CurrentUserRequest<'a> {
        CurrentUserRequest::new(self.client)
    }

    /// Creates a new session for a user in Jira. Once a session has been successfully created it can be used to access any of Jira's remote APIs and also the web UI by passing the appropriate HTTP Cookie header. Note that it is generally preferrable to use HTTP BASIC authentication with the REST API. However, this resource may be used to mimic the behaviour of Jira's log-in page (e.g. to display log-in errors to a user).
    pub fn login(&self, auth_params: AuthParams) -> LoginRequest<'a> {
        LoginRequest::new(self.client, auth_params)
    }

    /// Logs the current user out of Jira, destroying the existing session, if any.
    pub fn logout(&self) -> LogoutRequest<'a> {
        LogoutRequest::new(self.client)
    }
}

/// Returns information about the currently authenticated user's session. If the caller is not authenticated they will get a 401 Unauthorized status code.
pub struct CurrentUserRequest<'a> {
    client: &'a crate::core::Client,
}

impl<'a> CurrentUserRequest<'a> {
    fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let config = crate::core::RequestConfig::new(crate::core::Method::GET, "/rest/auth/1/session".to_owned());

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<CurrentUser> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Creates a new session for a user in Jira. Once a session has been successfully created it can be used to access any of Jira's remote APIs and also the web UI by passing the appropriate HTTP Cookie header. Note that it is generally preferrable to use HTTP BASIC authentication with the REST API. However, this resource may be used to mimic the behaviour of Jira's log-in page (e.g. to display log-in errors to a user).
pub struct LoginRequest<'a> {
    client: &'a crate::core::Client,
    auth_params: AuthParams,
}

impl<'a> LoginRequest<'a> {
    fn new(client: &'a crate::core::Client, auth_params: AuthParams) -> Self {
        Self { client, auth_params }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config = crate::core::RequestConfig::new(crate::core::Method::POST, "/rest/auth/1/session".to_owned());

        let body = match serde_json::to_value(&self.auth_params)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<AuthSuccess> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Logs the current user out of Jira, destroying the existing session, if any.
pub struct LogoutRequest<'a> {
    client: &'a crate::core::Client,
}

impl<'a> LogoutRequest<'a> {
    fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let config = crate::core::RequestConfig::new(crate::core::Method::DELETE, "/rest/auth/1/session".to_owned());

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<()> {
        self.client.send_empty(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}
