// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::super::models::*;

/// The Terminology operations.
pub struct TerminologyService<'a> {
    client: &'a crate::core::Client,
}

impl<'a> TerminologyService<'a> {
    pub(crate) fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// Returns a list of all defined names for the default words 'epic' and 'sprint'
    pub fn get_all_terminology_entries(&self) -> GetAllTerminologyEntriesRequest<'a> {
        GetAllTerminologyEntriesRequest::new(self.client)
    }

    /// Change epic/sprint names from {originalName} to {newName}. The {newName} will be displayed in Jira instead of {originalName}
    /// {"originalName"} must be equal to "epic" or "sprint".
    /// There can be only one entry per unique {"originalName"}.
    /// {"newName"} can only consist of alphanumeric characters and spaces e.g. {"newName": "iteration number 2"}.
    /// {"newName"} must be between 1 to 100 characters.
    /// It can't use the already defined {"newName"} values or restricted JQL words.
    /// To reset {"newName"} to the default value, enter the {"originalName"} value as the value for {"newName"}. For example, if you want to return to {"originalName": "sprint"}, enter {"newName": "sprint"}.
    pub fn set_terminology_entries(&self, terminology_request: TerminologyRequest) -> SetTerminologyEntriesRequest<'a> {
        SetTerminologyEntriesRequest::new(self.client, terminology_request)
    }

    /// Returns epic or sprint name as specified in the {originalName} path param
    pub fn get_terminology_entry(&self, original_name: impl Into<String>) -> GetTerminologyEntryRequest<'a> {
        GetTerminologyEntryRequest::new(self.client, original_name)
    }
}

/// Returns a list of all defined names for the default words 'epic' and 'sprint'
pub struct GetAllTerminologyEntriesRequest<'a> {
    client: &'a crate::core::Client,
}

impl<'a> GetAllTerminologyEntriesRequest<'a> {
    fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let config =
            crate::core::RequestConfig::new(crate::core::Method::GET, "/rest/api/2/terminology/entries".to_owned());

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<Vec<TerminologyResponse>> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Change epic/sprint names from {originalName} to {newName}. The {newName} will be displayed in Jira instead of {originalName}
/// {"originalName"} must be equal to "epic" or "sprint".
/// There can be only one entry per unique {"originalName"}.
/// {"newName"} can only consist of alphanumeric characters and spaces e.g. {"newName": "iteration number 2"}.
/// {"newName"} must be between 1 to 100 characters.
/// It can't use the already defined {"newName"} values or restricted JQL words.
/// To reset {"newName"} to the default value, enter the {"originalName"} value as the value for {"newName"}. For example, if you want to return to {"originalName": "sprint"}, enter {"newName": "sprint"}.
pub struct SetTerminologyEntriesRequest<'a> {
    client: &'a crate::core::Client,
    terminology_request: TerminologyRequest,
}

impl<'a> SetTerminologyEntriesRequest<'a> {
    fn new(client: &'a crate::core::Client, terminology_request: TerminologyRequest) -> Self {
        Self {
            client,
            terminology_request,
        }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let mut config =
            crate::core::RequestConfig::new(crate::core::Method::POST, "/rest/api/2/terminology/entries".to_owned());

        let body = match serde_json::to_value(&self.terminology_request)? {
            serde_json::Value::Object(object) => object,
            _ => serde_json::Map::new(),
        };

        config.body = Some(crate::core::Body::Json(serde_json::Value::Object(body)));

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<serde_json::Value> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}

/// Returns epic or sprint name as specified in the {originalName} path param
pub struct GetTerminologyEntryRequest<'a> {
    client: &'a crate::core::Client,
    original_name: String,
}

impl<'a> GetTerminologyEntryRequest<'a> {
    fn new(client: &'a crate::core::Client, original_name: impl Into<String>) -> Self {
        Self {
            client,
            original_name: original_name.into(),
        }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let config = crate::core::RequestConfig::new(
            crate::core::Method::GET,
            format!("/rest/api/2/terminology/entries/{}", self.original_name),
        );

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<TerminologyResponse> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}
