// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

crate::open_enum! {
    pub enum UnclaimedDomainResponseKey {
        ForbiddenUnclaimedDomain => "forbidden.unclaimedDomain",
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UnclaimedDomainResponseContext {
    pub domain: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UnclaimedDomainResponse {
    pub key: UnclaimedDomainResponseKey,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context: Option<UnclaimedDomainResponseContext>,
}
