// @generated by apis-code-gen. Do not edit: change the generator or the specification.

// A service takes its name from the tag the specification gave it, and one document names a
// tag after the surface itself.
#![allow(clippy::module_inception)]
#![allow(clippy::doc_lazy_continuation)]

mod external_teams;
mod team_members;
mod teams;

pub use external_teams::*;
pub use team_members::*;
pub use teams::*;
