// @generated. Do not edit: change the generator or the specification.

#![allow(clippy::doc_lazy_continuation)]

mod application_link;
mod archived_object;
mod archived_objects_page;
mod asset_object;
mod asset_object_extended;
mod asset_object_in;
mod attachment;
mod avatar;
mod comment;
mod confluence_page;
mod confluence_space;
mod default_type;
mod group;
mod icon;
mod index_integrity_out;
mod index_path;
mod index_persist_response;
mod js_tree_position;
mod link;
mod object_attribute;
mod object_attribute_in;
mod object_attribute_value;
mod object_attribute_value_in;
mod object_filter_params;
mod object_filter_values;
mod object_filters;
mod object_history;
mod object_iql_filter_param;
mod object_list_result;
mod object_schema;
mod object_schema_in;
mod object_schema_list;
mod object_type;
mod object_type_attribute;
mod object_type_attribute_in;
mod object_type_attributes_to_display;
mod object_type_in;
mod object_type_inheritance_tree;
mod progress_out;
mod project;
mod reference_type;
mod reference_type_object_info;
mod schema_stats;
mod status_type;
mod ticket;
mod ticket_priority;
mod ticket_status;
mod ticket_type;
mod tickets;
mod uploaded_attachment;
mod user;
mod version;

pub use application_link::*;
pub use archived_object::*;
pub use archived_objects_page::*;
pub use asset_object::*;
pub use asset_object_extended::*;
pub use asset_object_in::*;
pub use attachment::*;
pub use avatar::*;
pub use comment::*;
pub use confluence_page::*;
pub use confluence_space::*;
pub use default_type::*;
pub use group::*;
pub use icon::*;
pub use index_integrity_out::*;
pub use index_path::*;
pub use index_persist_response::*;
pub use js_tree_position::*;
pub use link::*;
pub use object_attribute::*;
pub use object_attribute_in::*;
pub use object_attribute_value::*;
pub use object_attribute_value_in::*;
pub use object_filter_params::*;
pub use object_filter_values::*;
pub use object_filters::*;
pub use object_history::*;
pub use object_iql_filter_param::*;
pub use object_list_result::*;
pub use object_schema::*;
pub use object_schema_in::*;
pub use object_schema_list::*;
pub use object_type::*;
pub use object_type_attribute::*;
pub use object_type_attribute_in::*;
pub use object_type_attributes_to_display::*;
pub use object_type_in::*;
pub use object_type_inheritance_tree::*;
pub use progress_out::*;
pub use project::*;
pub use reference_type::*;
pub use reference_type_object_info::*;
pub use schema_stats::*;
pub use status_type::*;
pub use ticket::*;
pub use ticket_priority::*;
pub use ticket_status::*;
pub use ticket_type::*;
pub use tickets::*;
pub use uploaded_attachment::*;
pub use user::*;
pub use version::*;
