// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::super::models::*;

/// The Usage operations.
pub struct UsageService<'a> {
    client: &'a crate::core::Client,
}

impl<'a> UsageService<'a> {
    pub(crate) fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// Retrieves comprehensive usage statistics for the current tenant including total object counts and a per-schema breakdown for billing and analytics.
    pub fn get_tenant_usage_info(&self) -> GetTenantUsageInfoRequest<'a> {
        GetTenantUsageInfoRequest::new(self.client)
    }
}

/// Retrieves comprehensive usage statistics for the current tenant including total object counts and a per-schema breakdown for billing and analytics.
pub struct GetTenantUsageInfoRequest<'a> {
    client: &'a crate::core::Client,
}

impl<'a> GetTenantUsageInfoRequest<'a> {
    fn new(client: &'a crate::core::Client) -> Self {
        Self { client }
    }

    /// The request as the transport will send it.
    pub fn config(&self) -> crate::core::Result<crate::core::RequestConfig> {
        let config = crate::core::RequestConfig::new(crate::core::Method::GET, "/usage".to_owned());

        Ok(config)
    }

    /// Sends the request.
    pub async fn send(self) -> crate::core::Result<TenantUsageResponse> {
        self.client.send(&self.config()?).await
    }

    /// Sends the request and hands back the body unmodelled.
    pub async fn send_raw(self) -> crate::core::Result<serde_json::Value> {
        self.client.send_raw(&self.config()?).await
    }
}
