// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

/// Used to create object schema
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ObjectSchemaIn {
    pub name: String,
    #[serde(rename = "objectSchemaKey")]
    pub object_schema_key: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}
