// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AttachmentMeta {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Upload limit in bytes
    #[serde(rename = "uploadLimit", default, skip_serializing_if = "Option::is_none")]
    pub upload_limit: Option<i64>,
}
