// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AvailableProjectsRequest {
    #[serde(rename = "ignoredProjectIds", default, skip_serializing_if = "Option::is_none")]
    pub ignored_project_ids: Option<Vec<String>>,
}
