// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IssueUpdate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fields: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "historyMetadata", default, skip_serializing_if = "Option::is_none")]
    pub history_metadata: Option<HistoryMetadata>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub properties: Option<Vec<EntityProperty>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transition: Option<Transition>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub update: Option<std::collections::HashMap<String, serde_json::Value>>,
}
