// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RemoveWorkflowRequest {
    #[serde(rename = "nextDefaultWorkflow", default, skip_serializing_if = "Option::is_none")]
    pub next_default_workflow: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workflow: Option<String>,
}
