// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserIssueRelevance {
    #[serde(rename = "avatarUrls", default, skip_serializing_if = "Option::is_none")]
    pub avatar_urls: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "displayName", default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "emailAddress", default, skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
    #[serde(
        rename = "highestIssueInvolvementRank",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub highest_issue_involvement_rank: Option<i64>,
    #[serde(rename = "issueInvolvements", default, skip_serializing_if = "Option::is_none")]
    pub issue_involvements: Option<Vec<IssueInvolvement>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(
        rename = "latestCommentCreationTime",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub latest_comment_creation_time: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "self", default, skip_serializing_if = "Option::is_none")]
    pub self_: Option<String>,
}
