// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SlaInformationOngoingCycle {
    #[serde(rename = "breachTime", default, skip_serializing_if = "Option::is_none")]
    pub breach_time: Option<Date>,
    /// Indicates whether the SLA has been breached (true) or not (false).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub breached: Option<bool>,
    #[serde(rename = "elapsedTime", default, skip_serializing_if = "Option::is_none")]
    pub elapsed_time: Option<Duration>,
    #[serde(rename = "goalDuration", default, skip_serializing_if = "Option::is_none")]
    pub goal_duration: Option<Duration>,
    /// Indicates whether the SLA is paused (true) or not (false).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paused: Option<bool>,
    #[serde(rename = "remainingTime", default, skip_serializing_if = "Option::is_none")]
    pub remaining_time: Option<Duration>,
    #[serde(rename = "startTime", default, skip_serializing_if = "Option::is_none")]
    pub start_time: Option<Date>,
    /// Indicates whether the SLA it timed during calendared working hours only (true) or not (false).
    #[serde(rename = "withinCalendarHours", default, skip_serializing_if = "Option::is_none")]
    pub within_calendar_hours: Option<bool>,
}
