// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

/// The container that the board is located in.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BoardLocation {
    #[serde(rename = "avatarURI", default, skip_serializing_if = "Option::is_none")]
    pub avatar_uri: Option<String>,
    #[serde(rename = "displayName", default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "projectId", default, skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i64>,
    #[serde(rename = "projectKey", default, skip_serializing_if = "Option::is_none")]
    pub project_key: Option<String>,
    #[serde(rename = "projectName", default, skip_serializing_if = "Option::is_none")]
    pub project_name: Option<String>,
    #[serde(rename = "projectTypeKey", default, skip_serializing_if = "Option::is_none")]
    pub project_type_key: Option<String>,
    #[serde(rename = "userAccountId", default, skip_serializing_if = "Option::is_none")]
    pub user_account_id: Option<String>,
    #[serde(rename = "userId", default, skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
}
