// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

crate::open_enum! {
    /// The FeatureFlagData schema version used for this flag data.
    ///
    /// Placeholder to support potential schema changes in the future.
    pub enum GetFeatureFlagByIdSchemaVersion {
        N10 => "1.0",
    }
}

/// Information about the rollout of a Feature Flag in an environment (or in summary).
///
/// Only one of 'percentage', 'text', or 'rules' should be provided. They will be used in that order if multiple are present.
///
/// This information may be presented to the user in the UI.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetFeatureFlagByIdSummaryStatusRollout {
    /// If the Feature Flag rollout is a simple percentage rollout
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percentage: Option<f64>,
    /// A text status to display that represents the rollout. This could be e.g. a named cohort.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// A count of the number of rules active for this Feature Flag in an environment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rules: Option<i64>,
}

/// Status information about a single Feature Flag.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetFeatureFlagByIdSummaryStatus {
    /// Whether the Feature Flag is enabled in the given environment (or in summary).
    ///
    /// Enabled may imply a partial rollout, which can be described using the 'rollout' field.
    pub enabled: bool,
    /// The value served by this Feature Flag when it is disabled. This could be the actual value or an alias, as appropriate.
    ///
    /// This value may be presented to the user in the UI.
    #[serde(rename = "defaultValue", default, skip_serializing_if = "Option::is_none")]
    pub default_value: Option<String>,
    /// Information about the rollout of a Feature Flag in an environment (or in summary).
    ///
    /// Only one of 'percentage', 'text', or 'rules' should be provided. They will be used in that order if multiple are present.
    ///
    /// This information may be presented to the user in the UI.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rollout: Option<GetFeatureFlagByIdSummaryStatusRollout>,
}

/// Summary information for a single Feature Flag.
///
/// Providers may elect to provide information from a specific environment, or they may choose to 'roll up' information from across multiple environments - whatever makes most sense in the Provider system.
///
/// This is the summary information that will be presented to the user on e.g. the Jira issue screen.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetFeatureFlagByIdSummary {
    /// A URL users can use to link to a summary view of this flag, if appropriate.
    ///
    /// This could be any location that makes sense in the Provider system (e.g. if the summary information comes from a specific environment, it might make sense to link the user to the flag in that environment).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Status information about a single Feature Flag.
    pub status: GetFeatureFlagByIdSummaryStatus,
    /// The last-updated timestamp to present to the user as a summary of the state of the Feature Flag.
    ///
    /// Providers may choose to supply the last-updated timestamp from a specific environment, or the 'most recent' last-updated timestamp across all environments - whatever makes sense in the Provider system.
    ///
    /// Expected format is an RFC3339 formatted string.
    #[serde(rename = "lastUpdated", deserialize_with = "crate::core::deserialize_required_timestamp")]
    pub last_updated: String,
}

crate::open_enum! {
    /// The 'type' or 'category' of environment this environment belongs to.
    pub enum GetFeatureFlagByIdDetailsEnvironmentType {
        Development => "development",
        Testing => "testing",
        Staging => "staging",
        Production => "production",
    }
}

/// Details of a single environment.
///
/// At the simplest this must be the name of the environment.
///
/// Ideally there is also type information which may be used to group data from multiple Feature Flags and other entities for visualisation in the UI.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetFeatureFlagByIdDetailsEnvironment {
    /// The name of the environment.
    pub name: String,
    /// The 'type' or 'category' of environment this environment belongs to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<GetFeatureFlagByIdDetailsEnvironmentType>,
}

/// Information about the rollout of a Feature Flag in an environment (or in summary).
///
/// Only one of 'percentage', 'text', or 'rules' should be provided. They will be used in that order if multiple are present.
///
/// This information may be presented to the user in the UI.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetFeatureFlagByIdDetailsStatusRollout {
    /// If the Feature Flag rollout is a simple percentage rollout
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percentage: Option<f64>,
    /// A text status to display that represents the rollout. This could be e.g. a named cohort.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// A count of the number of rules active for this Feature Flag in an environment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rules: Option<i64>,
}

/// Status information about a single Feature Flag.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetFeatureFlagByIdDetailsStatus {
    /// Whether the Feature Flag is enabled in the given environment (or in summary).
    ///
    /// Enabled may imply a partial rollout, which can be described using the 'rollout' field.
    pub enabled: bool,
    /// The value served by this Feature Flag when it is disabled. This could be the actual value or an alias, as appropriate.
    ///
    /// This value may be presented to the user in the UI.
    #[serde(rename = "defaultValue", default, skip_serializing_if = "Option::is_none")]
    pub default_value: Option<String>,
    /// Information about the rollout of a Feature Flag in an environment (or in summary).
    ///
    /// Only one of 'percentage', 'text', or 'rules' should be provided. They will be used in that order if multiple are present.
    ///
    /// This information may be presented to the user in the UI.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rollout: Option<GetFeatureFlagByIdDetailsStatusRollout>,
}

/// Details of a Feature Flag for a single environment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetFeatureFlagByIdDetails {
    /// A URL users can use to link to this Feature Flag, in this environment.
    pub url: String,
    /// The last-updated timestamp for this Feature Flag, in this environment.
    ///
    /// Expected format is an RFC3339 formatted string.
    #[serde(rename = "lastUpdated", deserialize_with = "crate::core::deserialize_required_timestamp")]
    pub last_updated: String,
    /// Details of a single environment.
    ///
    /// At the simplest this must be the name of the environment.
    ///
    /// Ideally there is also type information which may be used to group data from multiple Feature Flags and other entities for visualisation in the UI.
    pub environment: GetFeatureFlagByIdDetailsEnvironment,
    /// Status information about a single Feature Flag.
    pub status: GetFeatureFlagByIdDetailsStatus,
}

/// Data related to a single Feature Flag, across any Environment that the flag is present in.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetFeatureFlagById {
    /// The FeatureFlagData schema version used for this flag data.
    ///
    /// Placeholder to support potential schema changes in the future.
    #[serde(rename = "schemaVersion", default, skip_serializing_if = "Option::is_none")]
    pub schema_version: Option<GetFeatureFlagByIdSchemaVersion>,
    /// The identifier for the Feature Flag. Must be unique for a given Provider.
    pub id: String,
    /// The identifier that users would use to reference the Feature Flag in their source code etc.
    ///
    /// Will be made available via the UI for users to copy into their source code etc.
    pub key: String,
    /// An ID used to apply an ordering to updates for this Feature Flag in the case of out-of-order receipt of update requests.
    ///
    /// This can be any monotonically increasing number. A suggested implementation is to use epoch millis from the Provider system, but other alternatives are valid (e.g. a Provider could store a counter against each Feature Flag and increment that on each update to Jira).
    ///
    /// Updates for a Feature Flag that are received with an updateSqeuenceId lower than what is currently stored will be ignored.
    #[serde(rename = "updateSequenceId")]
    pub update_sequence_id: i64,
    /// The human-readable name for the Feature Flag. Will be shown in the UI.
    ///
    /// If not provided, will use the ID for display.
    #[serde(rename = "displayName", default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The Jira issue keys or IDs to associate the feature flag with.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub associations: Option<Vec<IssueIdOrKeysAssociation>>,
    /// Summary information for a single Feature Flag.
    ///
    /// Providers may elect to provide information from a specific environment, or they may choose to 'roll up' information from across multiple environments - whatever makes most sense in the Provider system.
    ///
    /// This is the summary information that will be presented to the user on e.g. the Jira issue screen.
    pub summary: GetFeatureFlagByIdSummary,
    /// Detail information for this Feature Flag.
    ///
    /// This may be information for each environment the Feature Flag is defined in or a selection of environments made by the user, as appropriate.
    pub details: Vec<GetFeatureFlagByIdDetails>,
}
