// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

crate::open_enum! {
    pub enum GetRepositoryCommitsFlags {
        MERGECOMMIT => "MERGE_COMMIT",
    }
}

/// Describes the author of a particular entity
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetRepositoryCommitsAuthor {
    /// Deprecated. The name of this user in a format suitable for display. Max length is 255 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The email address of the user. Used to associate the user with a Jira user. Max length is 255 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Deprecated. The username of the user. Used to associate the user with a Jira user if there are multiple users for a given email. Max length is 255 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Deprecated. The URL of the profile for this user. Max length is 2000 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Deprecated. The URL of the avatar for this user. Max length is 2000 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
}

crate::open_enum! {
    /// The operation performed on this file
    pub enum GetRepositoryCommitsFilesChangeType {
        ADDED => "ADDED",
        COPIED => "COPIED",
        DELETED => "DELETED",
        MODIFIED => "MODIFIED",
        MOVED => "MOVED",
        UNKNOWN => "UNKNOWN",
    }
}

/// Describes changes to a file
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetRepositoryCommitsFiles {
    /// The path of the file. Max length is 1024 characters.
    pub path: String,
    /// The URL of this file. Max length is 2000 characters.
    pub url: String,
    /// The operation performed on this file
    #[serde(rename = "changeType")]
    pub change_type: GetRepositoryCommitsFilesChangeType,
    /// Number of lines added to the file
    #[serde(rename = "linesAdded")]
    pub lines_added: i64,
    /// Number of lines removed from the file
    #[serde(rename = "linesRemoved")]
    pub lines_removed: i64,
}

/// Represents a commit in the version control system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetRepositoryCommits {
    /// The identifier or hash of the commit. Will be used for cross entity linking. Must be unique for all commits within a repository, i.e., only one commit can have ID 'X' in repository 'Y'. But adding, e.g., a branch with ID 'X' to repository 'Y' is acceptable. Only alphanumeric characters, and '~.-_', are allowed. Max length is 1024 characters
    pub id: String,
    /// The Jira issue keys or IDs to associate the commit with.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub associations: Option<Vec<IssueIdOrKeysAssociation>>,
    /// An ID used to apply an ordering to updates for this entity in the case of out-of-order receipt of update requests. This can be any monotonically increasing number. A suggested implementation is to use epoch millis from the provider system, but other alternatives are valid (e.g. a provider could store a counter against each entity and increment that on each update to Jira). Updates for an entity that are received with an updateSqeuenceId lower than what is currently stored will be ignored.
    #[serde(rename = "updateSequenceId")]
    pub update_sequence_id: i64,
    /// The set of flags for this commit
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flags: Option<Vec<GetRepositoryCommitsFlags>>,
    /// The commit message. Max length is 1024 characters. If anything longer is supplied, it will be truncated down to 1024 characters.
    pub message: String,
    /// Describes the author of a particular entity
    pub author: GetRepositoryCommitsAuthor,
    /// The total number of files added, removed, or modified by this commit
    #[serde(rename = "fileCount")]
    pub file_count: i64,
    /// The URL of this commit. Max length is 2000 characters.
    pub url: String,
    /// List of file changes. Max number of files is 10. Currently, only the first 5 files are shown (sorted by path) in the UI. This UI behavior may change without notice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub files: Option<Vec<GetRepositoryCommitsFiles>>,
    /// The author timestamp of this commit. Formatted as a UTC ISO 8601 date time format.
    #[serde(rename = "authorTimestamp")]
    pub author_timestamp: String,
    /// Shortened identifier for this commit, used for display. Max length is 255 characters.
    #[serde(rename = "displayId")]
    pub display_id: String,
}

crate::open_enum! {
    pub enum GetRepositoryBranchesLastCommitFlags {
        MERGECOMMIT => "MERGE_COMMIT",
    }
}

/// Describes the author of a particular entity
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetRepositoryBranchesLastCommitAuthor {
    /// Deprecated. The name of this user in a format suitable for display. Max length is 255 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The email address of the user. Used to associate the user with a Jira user. Max length is 255 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Deprecated. The username of the user. Used to associate the user with a Jira user if there are multiple users for a given email. Max length is 255 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Deprecated. The URL of the profile for this user. Max length is 2000 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Deprecated. The URL of the avatar for this user. Max length is 2000 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
}

crate::open_enum! {
    /// The operation performed on this file
    pub enum GetRepositoryBranchesLastCommitFilesChangeType {
        ADDED => "ADDED",
        COPIED => "COPIED",
        DELETED => "DELETED",
        MODIFIED => "MODIFIED",
        MOVED => "MOVED",
        UNKNOWN => "UNKNOWN",
    }
}

/// Describes changes to a file
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetRepositoryBranchesLastCommitFiles {
    /// The path of the file. Max length is 1024 characters.
    pub path: String,
    /// The URL of this file. Max length is 2000 characters.
    pub url: String,
    /// The operation performed on this file
    #[serde(rename = "changeType")]
    pub change_type: GetRepositoryBranchesLastCommitFilesChangeType,
    /// Number of lines added to the file
    #[serde(rename = "linesAdded")]
    pub lines_added: i64,
    /// Number of lines removed from the file
    #[serde(rename = "linesRemoved")]
    pub lines_removed: i64,
}

/// Represents a commit in the version control system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetRepositoryBranchesLastCommit {
    /// The identifier or hash of the commit. Will be used for cross entity linking. Must be unique for all commits within a repository, i.e., only one commit can have ID 'X' in repository 'Y'. But adding, e.g., a branch with ID 'X' to repository 'Y' is acceptable. Only alphanumeric characters, and '~.-_', are allowed. Max length is 1024 characters
    pub id: String,
    /// List of issues keys that this entity is associated with. They must be valid Jira issue keys.
    #[serde(rename = "issueKeys")]
    pub issue_keys: Vec<String>,
    /// An ID used to apply an ordering to updates for this entity in the case of out-of-order receipt of update requests. This can be any monotonically increasing number. A suggested implementation is to use epoch millis from the provider system, but other alternatives are valid (e.g. a provider could store a counter against each entity and increment that on each update to Jira). Updates for an entity that are received with an updateSqeuenceId lower than what is currently stored will be ignored.
    #[serde(rename = "updateSequenceId")]
    pub update_sequence_id: i64,
    /// The set of flags for this commit
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flags: Option<Vec<GetRepositoryBranchesLastCommitFlags>>,
    /// The commit message. Max length is 1024 characters. If anything longer is supplied, it will be truncated down to 1024 characters.
    pub message: String,
    /// Describes the author of a particular entity
    pub author: GetRepositoryBranchesLastCommitAuthor,
    /// The total number of files added, removed, or modified by this commit
    #[serde(rename = "fileCount")]
    pub file_count: i64,
    /// The URL of this commit. Max length is 2000 characters.
    pub url: String,
    /// List of file changes. Max number of files is 10. Currently, only the first 5 files are shown (sorted by path) in the UI. This UI behavior may change without notice.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub files: Option<Vec<GetRepositoryBranchesLastCommitFiles>>,
    /// The author timestamp of this commit. Formatted as a UTC ISO 8601 date time format.
    #[serde(rename = "authorTimestamp")]
    pub author_timestamp: String,
    /// Shortened identifier for this commit, used for display. Max length is 255 characters.
    #[serde(rename = "displayId")]
    pub display_id: String,
}

/// Represents a branch in the version control system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetRepositoryBranches {
    /// The ID of this entity. Will be used for cross entity linking. Must be unique by entity type within a repository, i.e., only one commit can have ID 'X' in repository 'Y'. But adding, e.g., a branch with ID 'X' to repository 'Y' is acceptable. Only alphanumeric characters, and '~.-_', are allowed. Max length is 1024 characters.
    pub id: String,
    /// The Jira issue keys or IDs to associate the branch with.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub associations: Option<Vec<IssueIdOrKeysAssociation>>,
    /// An ID used to apply an ordering to updates for this entity in the case of out-of-order receipt of update requests. This can be any monotonically increasing number. A suggested implementation is to use epoch millis from the provider system, but other alternatives are valid (e.g. a provider could store a counter against each entity and increment that on each update to Jira). Updates for an entity that are received with an updateSqeuenceId lower than what is currently stored will be ignored.
    #[serde(rename = "updateSequenceId")]
    pub update_sequence_id: i64,
    /// The name of the branch. Max length is 512 characters.
    pub name: String,
    /// Represents a commit in the version control system.
    #[serde(rename = "lastCommit")]
    pub last_commit: GetRepositoryBranchesLastCommit,
    /// The URL of the page for creating a pull request from this branch. Max length is 2000 characters.
    #[serde(rename = "createPullRequestUrl", default, skip_serializing_if = "Option::is_none")]
    pub create_pull_request_url: Option<String>,
    /// The URL of the branch. Max length is 2000 characters.
    pub url: String,
}

crate::open_enum! {
    /// The status of the pull request. In the case of concurrent updates, priority is given in the order OPEN, MERGED, DECLINED, UNKNOWN
    pub enum GetRepositoryPullRequestsStatus {
        OPEN => "OPEN",
        MERGED => "MERGED",
        DECLINED => "DECLINED",
        UNKNOWN => "UNKNOWN",
    }
}

/// Describes the author of a particular entity
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetRepositoryPullRequestsAuthor {
    /// Deprecated. The name of this user in a format suitable for display. Max length is 255 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The email address of the user. Used to associate the user with a Jira user. Max length is 255 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Deprecated. The username of the user. Used to associate the user with a Jira user if there are multiple users for a given email. Max length is 255 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Deprecated. The URL of the profile for this user. Max length is 2000 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Deprecated. The URL of the avatar for this user. Max length is 2000 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
}

crate::open_enum! {
    /// The approval status of this reviewer, default is UNAPPROVED.
    pub enum GetRepositoryPullRequestsReviewersApprovalStatus {
        APPROVED => "APPROVED",
        UNAPPROVED => "UNAPPROVED",
    }
}

/// The reviewer of a pull request
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetRepositoryPullRequestsReviewers {
    /// Deprecated. The name of this reviewer. Max length is 255 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The approval status of this reviewer, default is UNAPPROVED.
    #[serde(rename = "approvalStatus", default, skip_serializing_if = "Option::is_none")]
    pub approval_status: Option<GetRepositoryPullRequestsReviewersApprovalStatus>,
    /// Deprecated. The URL of the profile for this reviewer. Max length is 2000 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Deprecated. The URL of the avatar for this reviewer. Max length is 2000 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    /// The email address of this reviewer. Max length is 254 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The Atlassian Account ID (AAID) of this reviewer. Max length is 128 characters.
    #[serde(rename = "accountId", default, skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
}

/// Represents a pull request
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetRepositoryPullRequests {
    /// The ID of this entity. Will be used for cross entity linking. Must be unique by entity type within a repository, i.e., only one commit can have ID 'X' in repository 'Y'. But adding, e.g., a branch with ID 'X' to repository 'Y' is acceptable. Only alphanumeric characters, and '~.-_', are allowed. Max length is 1024 characters
    pub id: String,
    /// The Jira issue keys or IDs to associate the pull request with.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub associations: Option<Vec<IssueIdOrKeysAssociation>>,
    /// An ID used to apply an ordering to updates for this entity in the case of out-of-order receipt of update requests. This can be any monotonically increasing number. A suggested implementation is to use epoch millis from the provider system, but other alternatives are valid (e.g. a provider could store a counter against each entity and increment that on each update to Jira). Updates for an entity that are received with an updateSqeuenceId lower than what is currently stored will be ignored.
    #[serde(rename = "updateSequenceId")]
    pub update_sequence_id: i64,
    /// The status of the pull request. In the case of concurrent updates, priority is given in the order OPEN, MERGED, DECLINED, UNKNOWN
    pub status: GetRepositoryPullRequestsStatus,
    /// Title of the pull request. Max length is 1024 characters.
    pub title: String,
    /// Describes the author of a particular entity
    pub author: GetRepositoryPullRequestsAuthor,
    /// The number of comments on the pull request
    #[serde(rename = "commentCount")]
    pub comment_count: i64,
    /// The name of the source branch of this PR. Max length is 255 characters.
    #[serde(rename = "sourceBranch")]
    pub source_branch: String,
    /// The url of the source branch of this PR. This is used to match this PR against the branch. Max length is 2000 characters.
    #[serde(rename = "sourceBranchUrl", default, skip_serializing_if = "Option::is_none")]
    pub source_branch_url: Option<String>,
    /// The most recent update to this PR. Formatted as a UTC ISO 8601 date time format.
    #[serde(rename = "lastUpdate")]
    pub last_update: String,
    /// The name of destination branch of this PR. Max length is 255 characters.
    #[serde(rename = "destinationBranch", default, skip_serializing_if = "Option::is_none")]
    pub destination_branch: Option<String>,
    /// The url of the destination branch of this PR. Max length is 2000 characters.
    #[serde(rename = "destinationBranchUrl", default, skip_serializing_if = "Option::is_none")]
    pub destination_branch_url: Option<String>,
    /// The list of reviewers of this pull request
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reviewers: Option<Vec<GetRepositoryPullRequestsReviewers>>,
    /// The URL of this pull request. Max length is 2000 characters.
    pub url: String,
    /// Shortened identifier for this pull request, used for display. Max length is 255 characters.
    #[serde(rename = "displayId")]
    pub display_id: String,
}

/// Represents a repository, containing development information such as commits, pull requests, and branches.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetRepository {
    /// The name of this repository. Max length is 255 characters.
    pub name: String,
    /// Description of this repository. Max length is 1024 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The ID of the repository this repository was forked from, if it's a fork. Max length is 1024 characters.
    #[serde(rename = "forkOf", default, skip_serializing_if = "Option::is_none")]
    pub fork_of: Option<String>,
    /// The URL of this repository. Max length is 2000 characters.
    pub url: String,
    /// List of commits to update in this repository. Must not contain duplicate entity IDs. Maximum number of commits is 400
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commits: Option<Vec<GetRepositoryCommits>>,
    /// List of branches to update in this repository. Must not contain duplicate entity IDs. Maximum number of branches is 400.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub branches: Option<Vec<GetRepositoryBranches>>,
    /// List of pull requests to update in this repository. Must not contain duplicate entity IDs. Maximum number of pull requests is 400
    #[serde(rename = "pullRequests", default, skip_serializing_if = "Option::is_none")]
    pub pull_requests: Option<Vec<GetRepositoryPullRequests>>,
    /// The URL of the avatar for this repository. Max length is 2000 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    /// Description of the avatar for this repository. Max length is 1024 characters.
    #[serde(rename = "avatarDescription", default, skip_serializing_if = "Option::is_none")]
    pub avatar_description: Option<String>,
    /// The ID of this entity. Will be used for cross entity linking. Must be unique by entity type within a repository, i.e., only one commit can have ID 'X' in repository 'Y'. But adding, e.g., a branch with ID 'X' to repository 'Y' is acceptable. Only alphanumeric characters, and '~.-_', are allowed. Max length is 1024 characters.
    pub id: String,
    /// An ID used to apply an ordering to updates for this entity in the case of out-of-order receipt of update requests. This can be any monotonically increasing number. A suggested implementation is to use epoch millis from the provider system, but other alternatives are valid (e.g. a provider could store a counter against each entity and increment that on each update to Jira). Updates for an entity that are received with an updateSqeuenceId lower than what is currently stored will be ignored.
    #[serde(rename = "updateSequenceId")]
    pub update_sequence_id: i64,
}
