// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

/// The result of a successful store development information request
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StoreDevelopmentInformation {
    /// The IDs of devinfo entities that have been accepted for submission grouped by their repository IDs. Note that a devinfo entity that isn't updated due to it's updateSequenceId being out of order is not considered a failed submission.
    #[serde(rename = "acceptedDevinfoEntities", default, skip_serializing_if = "Option::is_none")]
    pub accepted_devinfo_entities: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// IDs of devinfo entities that have not been accepted for submission and caused error descriptions, usually due to a problem with the request data. The entities (if present) will be grouped by their repository id and type. Entity IDs are listed with errors associated with that devinfo entity that have prevented it being submitted.
    #[serde(rename = "failedDevinfoEntities", default, skip_serializing_if = "Option::is_none")]
    pub failed_devinfo_entities: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Issue keys that are not known on this Jira instance (if any). These may be invalid keys (e.g. `UTF-8` is sometimes incorrectly identified as a Jira issue key), or they may be for projects that no longer exist. If a devinfo entity has been associated with issue keys other than those in this array it will still be stored against those valid keys.
    #[serde(rename = "unknownIssueKeys", default, skip_serializing_if = "Option::is_none")]
    pub unknown_issue_keys: Option<Vec<String>>,
    /// Associations that are not known on this Jira instance (if any).
    ///
    /// These may be invalid keys (e.g. `UTF-8` is sometimes incorrectly identified as a Jira issue key), or they may be for projects that no longer exist.
    ///
    /// If a development information entity has been associated with any other association other than those in this array it will still be stored against those valid associations.
    /// If a development information entity was only associated with the associations in this array, it is deemed to be invalid and it won't be persisted.
    #[serde(rename = "unknownAssociations", default, skip_serializing_if = "Option::is_none")]
    pub unknown_associations: Option<Vec<IssueIdOrKeysAssociation>>,
}
