// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AttachmentCreate {
    #[serde(rename = "temporaryAttachmentIds", default, skip_serializing_if = "Option::is_none")]
    pub temporary_attachment_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    #[serde(rename = "additionalComment", default, skip_serializing_if = "Option::is_none")]
    pub additional_comment: Option<AdditionalComment>,
}
