// @generated. Do not edit: change the generator or the specification.

#![allow(clippy::doc_lazy_continuation)]

mod additional_comment;
mod approval;
mod approval_comment_config;
mod approval_condition;
mod approval_decision_request;
mod approver;
mod attachment;
mod attachment_create;
mod attachment_create_result;
mod attachment_link;
mod change_history;
mod change_item;
mod changelog;
mod comment;
mod comment_create;
mod create_temporary_web_attachment_result;
mod customer_create;
mod customer_organization;
mod customer_request;
mod customer_request_create_meta;
mod customer_request_field_value;
mod customer_request_link;
mod customer_request_status;
mod customer_transition;
mod customer_transition_execution;
mod date;
mod duration;
mod edit_meta;
mod field_meta;
mod file_part;
mod history_metadata;
mod history_metadata_participant;
mod included_fields;
mod issue;
mod json_type;
mod link_group;
mod opsbar;
mod organization;
mod organization_create;
mod organization_service_desk_update;
mod page;
mod paged_approval;
mod paged_comment;
mod paged_customer_request;
mod paged_customer_request_status;
mod paged_customer_transition;
mod paged_issue;
mod paged_link;
mod paged_organization;
mod paged_portal;
mod paged_queue;
mod paged_request_type;
mod paged_request_type_group;
mod paged_service_desk;
mod paged_sla_information;
mod paged_user;
mod portal;
mod properties;
mod queue;
mod queue_create;
mod request_create;
mod request_participant_update;
mod request_type;
mod request_type_allowed_entity;
mod request_type_create;
mod request_type_field;
mod request_type_field_value;
mod request_type_group;
mod request_type_icon;
mod request_type_icon_link;
mod request_type_permission;
mod request_type_permission_entity_request;
mod request_type_permission_request;
mod request_type_update;
mod self_link;
mod service_desk;
mod service_desk_customer_add;
mod service_desk_link;
mod simple_link;
mod sla_information;
mod sla_information_completed_cycle;
mod sla_information_ongoing_cycle;
mod software_info;
mod status_category_json;
mod status_json;
mod temporary_web_attachment;
mod transition;
mod user;
mod user_json;
mod user_link;
mod users_organization_update;

pub use additional_comment::*;
pub use approval::*;
pub use approval_comment_config::*;
pub use approval_condition::*;
pub use approval_decision_request::*;
pub use approver::*;
pub use attachment::*;
pub use attachment_create::*;
pub use attachment_create_result::*;
pub use attachment_link::*;
pub use change_history::*;
pub use change_item::*;
pub use changelog::*;
pub use comment::*;
pub use comment_create::*;
pub use create_temporary_web_attachment_result::*;
pub use customer_create::*;
pub use customer_organization::*;
pub use customer_request::*;
pub use customer_request_create_meta::*;
pub use customer_request_field_value::*;
pub use customer_request_link::*;
pub use customer_request_status::*;
pub use customer_transition::*;
pub use customer_transition_execution::*;
pub use date::*;
pub use duration::*;
pub use edit_meta::*;
pub use field_meta::*;
pub use file_part::*;
pub use history_metadata::*;
pub use history_metadata_participant::*;
pub use included_fields::*;
pub use issue::*;
pub use json_type::*;
pub use link_group::*;
pub use opsbar::*;
pub use organization::*;
pub use organization_create::*;
pub use organization_service_desk_update::*;
pub use page::*;
pub use paged_approval::*;
pub use paged_comment::*;
pub use paged_customer_request::*;
pub use paged_customer_request_status::*;
pub use paged_customer_transition::*;
pub use paged_issue::*;
pub use paged_link::*;
pub use paged_organization::*;
pub use paged_portal::*;
pub use paged_queue::*;
pub use paged_request_type::*;
pub use paged_request_type_group::*;
pub use paged_service_desk::*;
pub use paged_sla_information::*;
pub use paged_user::*;
pub use portal::*;
pub use properties::*;
pub use queue::*;
pub use queue_create::*;
pub use request_create::*;
pub use request_participant_update::*;
pub use request_type::*;
pub use request_type_allowed_entity::*;
pub use request_type_create::*;
pub use request_type_field::*;
pub use request_type_field_value::*;
pub use request_type_group::*;
pub use request_type_icon::*;
pub use request_type_icon_link::*;
pub use request_type_permission::*;
pub use request_type_permission_entity_request::*;
pub use request_type_permission_request::*;
pub use request_type_update::*;
pub use self_link::*;
pub use service_desk::*;
pub use service_desk_customer_add::*;
pub use service_desk_link::*;
pub use simple_link::*;
pub use sla_information::*;
pub use sla_information_completed_cycle::*;
pub use sla_information_ongoing_cycle::*;
pub use software_info::*;
pub use status_category_json::*;
pub use status_json::*;
pub use temporary_web_attachment::*;
pub use transition::*;
pub use user::*;
pub use user_json::*;
pub use user_link::*;
pub use users_organization_update::*;
