// @generated by apis-code-gen. Do not edit: change the generator or the specification.

use serde::{Deserialize, Serialize};

crate::open_enum! {
    pub enum RequestTypeAllowedEntityEntityType {
        USER => "USER",
        GROUP => "GROUP",
        ORGANIZATION => "ORGANIZATION",
    }
}

crate::open_enum! {
    pub enum RequestTypeAllowedEntityStatus {
        DELETED => "DELETED",
        REMOVED => "REMOVED",
        ACTIVE => "ACTIVE",
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RequestTypeAllowedEntity {
    #[serde(rename = "avatarUrl", default, skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<String>,
    #[serde(rename = "entityId", default, skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<String>,
    #[serde(rename = "entityType", default, skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<RequestTypeAllowedEntityEntityType>,
    #[serde(rename = "displayName", default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<RequestTypeAllowedEntityStatus>,
}
